from pathlib import Path

p=Path('studio/src/ProjectDocumentsWorkspace.tsx')
s=p.read_text()

old=""" const canvasRef=useRef<HTMLCanvasElement|null>(null);const imageRef=useRef<HTMLImageElement|null>(null);const stageRef=useRef<HTMLDivElement|null>(null);const viewportRef=useRef<HTMLDivElement|null>(null);const offsetSaveTimerRef=useRef<number|null>(null);const snapCanvasRef=useRef<HTMLCanvasElement|null>(null);"""
new=""" const canvasRef=useRef<HTMLCanvasElement|null>(null);const imageRef=useRef<HTMLImageElement|null>(null);const stageRef=useRef<HTMLDivElement|null>(null);const viewportRef=useRef<HTMLDivElement|null>(null);const offsetSaveTimerRef=useRef<number|null>(null);const snapCanvasRef=useRef<HTMLCanvasElement|null>(null);const touchPointRef=useRef<{pointerId:number;point:Point|null}|null>(null);"""
if old not in s: raise SystemExit('ref block not found')
s=s.replace(old,new,1)

old=""" function handleStageClick(e:React.PointerEvent<HTMLDivElement>){if(tool==='hand'||!attachment)return;let point=pointFromEvent(e);if(!point)return;const objectSnap=altGraphHeld(e);point=snapToDrawing(point,objectSnap);if(pending.length>=1&&!objectSnap)point=snapPoint(pending[0],point,e.shiftKey);const next=[...pending,point];if(tool==='angle'){if(next.length<3){setPending(next);return}setPending([]);const angle:AngleMeasurement={id:crypto.randomUUID(),center:next[0],a:next[1],b:next[2],label:'',description:'',visible:true,labelOffset:{x:0,y:0}};if(measuredAngle(angle)<0.1){setMessage('Vinkeln är för liten för att sparas.');return}updatePage({...pageState,angles:[...(pageState.angles||[]),angle]});return}if(next.length<2){setPending(next);return}setPending([]);if(tool==='calibrate'){const raw=window.prompt('Ange verkligt avstånd mellan punkterna i mm:','1000');if(!raw)return;const distanceMm=Number(raw.replace(',','.'));if(!Number.isFinite(distanceMm)||distanceMm<=0){setMessage('Ogiltigt kalibreringsmått.');return}updatePage({...pageState,calibration:{a:next[0],b:next[1],distanceMm}});setTool('hand');setMessage('Skalan är kalibrerad för den här sidan.');return}if(!pageState.calibration&&!pageState.scale){setMessage('Välj ritningsskala eller kalibrera innan du mäter.');return}updatePage({...pageState,measurements:[...pageState.measurements,{id:crypto.randomUUID(),a:next[0],b:next[1],label:'',description:'',visible:true,offset:0}]});}"""
new=""" function commitStagePoint(point:Point){const next=[...pending,point];if(tool==='angle'){if(next.length<3){setPending(next);return}setPending([]);const angle:AngleMeasurement={id:crypto.randomUUID(),center:next[0],a:next[1],b:next[2],label:'',description:'',visible:true,labelOffset:{x:0,y:0}};if(measuredAngle(angle)<0.1){setMessage('Vinkeln är för liten för att sparas.');return}updatePage({...pageState,angles:[...(pageState.angles||[]),angle]});return}if(next.length<2){setPending(next);return}setPending([]);if(tool==='calibrate'){const raw=window.prompt('Ange verkligt avstånd mellan punkterna i mm:','1000');if(!raw)return;const distanceMm=Number(raw.replace(',','.'));if(!Number.isFinite(distanceMm)||distanceMm<=0){setMessage('Ogiltigt kalibreringsmått.');return}updatePage({...pageState,calibration:{a:next[0],b:next[1],distanceMm}});setTool('hand');setMessage('Skalan är kalibrerad för den här sidan.');return}if(!pageState.calibration&&!pageState.scale){setMessage('Välj ritningsskala eller kalibrera innan du mäter.');return}updatePage({...pageState,measurements:[...pageState.measurements,{id:crypto.randomUUID(),a:next[0],b:next[1],label:'',description:'',visible:true,offset:0}]});}
 function resolvedPoint(e:React.PointerEvent<HTMLDivElement>){let point=pointFromEvent(e);if(!point)return null;const objectSnap=altGraphHeld(e);point=snapToDrawing(point,objectSnap);if(pending.length>=1&&!objectSnap)point=snapPoint(pending[0],point,e.shiftKey);return point}
 function handleStageClick(e:React.PointerEvent<HTMLDivElement>){if(e.pointerType==='touch'||tool==='hand'||!attachment)return;const point=resolvedPoint(e);if(point)commitStagePoint(point)}
 function handleStagePointerDown(e:React.PointerEvent<HTMLDivElement>){if(e.pointerType!=='touch'||tool==='hand'||!attachment)return;const point=resolvedPoint(e);if(!point)return;e.preventDefault();e.stopPropagation();touchPointRef.current={pointerId:e.pointerId,point};setCursorPoint(point);try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}}
 function handleStagePointerMove(e:React.PointerEvent<HTMLDivElement>){if(e.pointerType==='touch'&&touchPointRef.current?.pointerId===e.pointerId){e.preventDefault();e.stopPropagation();const point=resolvedPoint(e);if(point){touchPointRef.current.point=point;setCursorPoint(point)}return}const raw=tool==='hand'?null:pointFromEvent(e);setCursorPoint(previewPoint(raw,e.shiftKey,altGraphHeld(e)))}
 function handleStagePointerUp(e:React.PointerEvent<HTMLDivElement>){if(e.pointerType!=='touch'||touchPointRef.current?.pointerId!==e.pointerId)return;e.preventDefault();e.stopPropagation();const point=touchPointRef.current.point;touchPointRef.current=null;if(point)commitStagePoint(point);setCursorPoint(null);try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}}
 function handleStagePointerCancel(e:React.PointerEvent<HTMLDivElement>){if(e.pointerType!=='touch'||touchPointRef.current?.pointerId!==e.pointerId)return;touchPointRef.current=null;setCursorPoint(null);try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}}"""
if old not in s: raise SystemExit('handler block not found')
s=s.replace(old,new,1)

old="""<div ref={stageRef} className=\"drawingStage\" onPointerDown={handleStageClick} onPointerMove={e=>{const raw=tool==='hand'?null:pointFromEvent(e);setCursorPoint(previewPoint(raw,e.shiftKey,altGraphHeld(e)))}} onPointerLeave={()=>setCursorPoint(null)}>"""
new="""<div ref={stageRef} className=\"drawingStage\" onPointerDown={e=>{handleStagePointerDown(e);handleStageClick(e)}} onPointerMove={handleStagePointerMove} onPointerUp={handleStagePointerUp} onPointerCancel={handleStagePointerCancel} onPointerLeave={e=>{if(e.pointerType!=='touch')setCursorPoint(null)}}>"""
if old not in s: raise SystemExit('stage JSX block not found')
s=s.replace(old,new,1)

p.write_text(s)
