from pathlib import Path

# StudioShell
p=Path('studio/src/StudioShell.tsx')
s=p.read_text()
s=s.replace("import { MasterProjectsView } from './MasterProjectsView';\n", "import { MasterProjectsView } from './MasterProjectsView';\nimport { ProjectsView } from './ProjectsView';\n")
s=s.replace("type StudioView='project'|'project-documents'|'governing-documents'|'governing-mapping'|'master-projects'|'users'|'control-plan'|'graphical-plan'|'backup'|'system-workspaces';", "type StudioView='projects'|'project'|'new-project'|'project-documents'|'governing-documents'|'governing-mapping'|'users'|'control-plan'|'graphical-plan'|'backup'|'system-workspaces';")
s=s.replace("const[view,setView]=useState<StudioView>(()=>kaOnly?'control-plan':'project');", "const[view,setView]=useState<StudioView>(()=>kaOnly?'control-plan':'projects');")
s=s.replace(" function openCreatedProject(id:string){selectProject(id);void loadProjects(id);setView('project')}", " function openCreatedProject(id:string){selectProject(id);void loadProjects(id);setView('project')}\n function openProjectFromTree(id:string){selectProject(id);setView('project')}")
old=""" if(view==='project')return <div className=\"studioShell view-project\" data-system-admin={isSystemAdmin?'true':'false'}>{projectId?<><ProjectWorkspace projects={projects} projectId={projectId} onProjectChange={selectProject} onOpenProjectDocuments={()=>setView('project-documents')} onOpenGoverningDocuments={()=>setView('governing-documents')} onOpenGoverningMapping={()=>setView('governing-mapping')} mappingWarning={mappingWarning} onOpenMasterProjects={()=>setView('master-projects')}/><ProjectHierarchyIndicators key={`indicators-${statusVersion}`}/><ProjectHierarchyStatusV2 key={`status-${statusVersion}`}/><GoverningCompletionIndicator/><ProjectReportsMount projectId={projectId}/></>:<div className=\"workspaceEmpty\">Hämtar projekt…</div>}</div>;
 const master=view==='master-projects',systemWorkspaces=view==='system-workspaces',projectDocuments=view==='project-documents',mapping=view==='governing-mapping',users=view==='users',controlPlan=view==='control-plan',graphicalPlan=view==='graphical-plan',backup=view==='backup';
"""
new=""" if(view==='project')return <div className=\"studioShell view-project\" data-system-admin={isSystemAdmin?'true':'false'}>{projectId?<><ProjectWorkspace projects={projects} projectId={projectId} onProjectChange={selectProject} onOpenProjects={()=>setView('projects')} onOpenProjectDocuments={()=>setView('project-documents')} onOpenGoverningDocuments={()=>setView('governing-documents')} onOpenGoverningMapping={()=>setView('governing-mapping')} mappingWarning={mappingWarning}/><ProjectHierarchyIndicators key={`indicators-${statusVersion}`}/><ProjectHierarchyStatusV2 key={`status-${statusVersion}`}/><GoverningCompletionIndicator/><ProjectReportsMount projectId={projectId}/></>:<div className=\"workspaceEmpty\"><button onClick={()=>setView('projects')}>Till projekt</button></div>}</div>;
 const projectsView=view==='projects',newProject=view==='new-project',systemWorkspaces=view==='system-workspaces',projectDocuments=view==='project-documents',mapping=view==='governing-mapping',users=view==='users',controlPlan=view==='control-plan',graphicalPlan=view==='graphical-plan',backup=view==='backup';
"""
if old not in s: raise SystemExit('Studio project block not found')
s=s.replace(old,new,1)
s=s.replace("return <div className={`studioShell view-control-plan ${master?'view-master-projects':mapping?'view-governing-mapping':users?'view-users':controlPlan?'view-native-control-plan':graphicalPlan?'view-graphical-plan':backup?'view-backup':'view-governing-documents'}`}", "return <div className={`studioShell view-control-plan ${projectsView?'view-projects':newProject?'view-new-project':mapping?'view-governing-mapping':users?'view-users':controlPlan?'view-native-control-plan':graphicalPlan?'view-graphical-plan':backup?'view-backup':'view-governing-documents'}`}")
s=s.replace("<small>{systemWorkspaces?'System · Projektytor':master?'Masterprojekt':mapping?'Kartläggning':users?'Användare':controlPlan?'Kontrollplan':graphicalPlan?'Grafisk plan':backup?'Backup':projectDocuments?'Projektdokument':'Styrdokument'}</small>", "<small>{systemWorkspaces?'System · Projektytor':projectsView?'Projekt':newProject?'Nytt projekt':mapping?'Kartläggning':users?'Användare':controlPlan?'Kontrollplan':graphicalPlan?'Grafisk plan':backup?'Backup':projectDocuments?'Projektdokument':'Styrdokument'}</small>")
s=s.replace("{!master&&!systemWorkspaces&&<select value={projectId}", "{!systemWorkspaces&&<select value={projectId}")
s=s.replace("{master&&<div className=\"masterTopbarLabel\">Bibliotek</div>}", "")
s=s.replace("<button title=\"Projekt\" onClick={()=>setView('project')}>🌳<span>Projekt</span></button>", "<button className={projectsView||newProject?'active':''} title=\"Projekt\" onClick={()=>setView('projects')}>🌳<span>Projekt</span></button>")
s=s.replace("<button className={master?'active':''} title=\"Masterprojekt\" onClick={()=>setView('master-projects')}>🏠<span>Masterprojekt</span></button>", "")
old2="""<section className=\"controlPlanMainRegion\" aria-label={systemWorkspaces?'Systemadministration för projektytor':master?'Masterprojekt':mapping?`Kartläggning för ${current?.name||'projektet'}`:users?`Användare i ${current?.name||'projektet'}`:controlPlan?`Kontrollplan för ${current?.name||'projektet'}`:graphicalPlan?`Grafisk plan för ${current?.name||'projektet'}`:backup?`Backup för ${current?.name||'projektet'}`:`Styrdokument för ${current?.name||'projektet'}`}>{systemWorkspaces?<SystemWorkspacesView/>:master?<MasterProjectsView onProjectCreated={openCreatedProject} workspaceId={current?.workspaceId} workspaces={auth.user?.workspaces||[]}/>:projectId?(users?<ProjectUsersView projectId={projectId}/>:controlPlan?<ControlPlanReviewView projectId={projectId} projectName={current?.name} propertyDesignation={current?.property_designation}/>:graphicalPlan?<GraphicalPlanView projectId={projectId} projectName={current?.name}/>:backup?<ProjectBackupView projectId={projectId} projectName={current?.name}/>:projectDocuments?<ProjectDocumentsWorkspace projectId={projectId} projectName={current?.name}/>:mapping?<GoverningMappingView projectId={projectId}/>:<GoverningDocumentsWorkspace projectId={projectId} onOpenMapping={()=>setView('governing-mapping')}/>):<div className=\"empty\"><span>{users?'👥':controlPlan?'📋':graphicalPlan?'🕸️':backup?'💾':mapping?'🧭':'📚'}</span><h2>Inget projekt valt</h2></div>}</section>"""
new2="""<section className=\"controlPlanMainRegion\" aria-label={systemWorkspaces?'Systemadministration för projektytor':projectsView?'Projekt':newProject?'Nytt projekt':mapping?`Kartläggning för ${current?.name||'projektet'}`:users?`Användare i ${current?.name||'projektet'}`:controlPlan?`Kontrollplan för ${current?.name||'projektet'}`:graphicalPlan?`Grafisk plan för ${current?.name||'projektet'}`:backup?`Backup för ${current?.name||'projektet'}`:`Styrdokument för ${current?.name||'projektet'}`}>{systemWorkspaces?<SystemWorkspacesView/>:projectsView?<ProjectsView projects={projects} selectedProjectId={projectId} onOpenProject={openProjectFromTree} onNewProject={()=>setView('new-project')}/>:newProject?<MasterProjectsView onProjectCreated={openCreatedProject} workspaceId={current?.workspaceId} workspaces={auth.user?.workspaces||[]}/>:projectId?(users?<ProjectUsersView projectId={projectId}/>:controlPlan?<ControlPlanReviewView projectId={projectId} projectName={current?.name} propertyDesignation={current?.property_designation}/>:graphicalPlan?<GraphicalPlanView projectId={projectId} projectName={current?.name}/>:backup?<ProjectBackupView projectId={projectId} projectName={current?.name}/>:projectDocuments?<ProjectDocumentsWorkspace projectId={projectId} projectName={current?.name}/>:mapping?<GoverningMappingView projectId={projectId}/>:<GoverningDocumentsWorkspace projectId={projectId} onOpenMapping={()=>setView('governing-mapping')}/>):<div className=\"empty\"><span>{users?'👥':controlPlan?'📋':graphicalPlan?'🕸️':backup?'💾':mapping?'🧭':'📚'}</span><h2>Inget projekt valt</h2></div>}</section>"""
if old2 not in s: raise SystemExit('Studio main region block not found')
s=s.replace(old2,new2,1)
p.write_text(s)

# ProjectWorkspace
p=Path('studio/src/ProjectWorkspace.tsx')
s=p.read_text()
s=s.replace("type Props={projects:Project[];projectId:string;onProjectChange:(id:string)=>void;onOpenProjectDocuments:()=>void;onOpenGoverningDocuments:()=>void;onOpenGoverningMapping:()=>void;mappingWarning?:number;onOpenMasterProjects:()=>void};", "type Props={projects:Project[];projectId:string;onProjectChange:(id:string)=>void;onOpenProjects:()=>void;onOpenProjectDocuments:()=>void;onOpenGoverningDocuments:()=>void;onOpenGoverningMapping:()=>void;mappingWarning?:number};")
s=s.replace("export function ProjectWorkspace({projects,projectId,onProjectChange,onOpenProjectDocuments,onOpenGoverningDocuments,onOpenGoverningMapping,mappingWarning=0,onOpenMasterProjects}:Props)", "export function ProjectWorkspace({projects,projectId,onProjectChange,onOpenProjects,onOpenProjectDocuments,onOpenGoverningDocuments,onOpenGoverningMapping,mappingWarning=0}:Props)")
s=s.replace("<button className=\"active\" title=\"Projekt\">🌳<span>Projekt</span></button>", "<button className=\"active\" title=\"Projekt\" onClick={onOpenProjects}>🌳<span>Projekt</span></button>")
s=s.replace("<button title=\"Masterprojekt\" onClick={onOpenMasterProjects}>🏠<span>Masterprojekt</span></button>", "")
p.write_text(s)

# main.tsx css import
p=Path('studio/src/main.tsx')
s=p.read_text()
needle="import './project-workspace-v2.css';\n"
if needle not in s: raise SystemExit('main css marker not found')
s=s.replace(needle, needle+"import './projects-view.css';\n",1)
p.write_text(s)

# trigger
