from pathlib import Path

# 1) Keep only true project-tree pages in ProjectsView.
p=Path('studio/src/ProjectsView.tsx')
s=p.read_text()
s=s.replace(" {id:'conditions',label:'Projektvillkor',icon:'◆'},\n {id:'information',label:'Projektinformation',icon:'ℹ'},\n {id:'reports',label:'Rapporter',icon:'▥'},\n {id:'settings',label:'Inställningar',icon:'⚙'},\n", " {id:'conditions',label:'Projektvillkor',icon:'◆'},\n")
p.write_text(s)

# 2) Utility rail should navigate directly, not click hidden project-tree rows.
p=Path('studio/src/project-utility-rail.ts')
s=p.read_text()
s=s.replace("function syncActive(){const activeLabel=projectRows().find(row=>row.classList.contains('selected'))?.querySelector('.projectTreeLabel')?.textContent?.trim()||'';const nativeControlPlan=Boolean(document.querySelector('.studioShell.view-native-control-plan'));const graphicalPlan=Boolean(document.querySelector('.studioShell.view-graphical-plan'));const backup=Boolean(document.querySelector('.studioShell.view-backup'));const utilityActive=utilityItems.some(item=>item.label===activeLabel);for(const button of Array.from(document.querySelectorAll<HTMLButtonElement>('.rail .projectUtilityRailButton')))button.classList.toggle('active',button.dataset.utilityLabel===activeLabel||(nativeControlPlan&&button.dataset.utilityLabel==='Kontrollplan')||(graphicalPlan&&button.dataset.utilityLabel==='Grafisk plan')||(backup&&button.dataset.utilityLabel==='Backup'));const workspace=document.querySelector<HTMLElement>('.projectWorkspace');workspace?.classList.toggle('projectUtilityView',utilityActive)}",
"function syncActive(){const activeLabel=projectRows().find(row=>row.classList.contains('selected'))?.querySelector('.projectTreeLabel')?.textContent?.trim()||'';const shell=document.querySelector<HTMLElement>('.studioShell');const projectPage=shell?.dataset.projectPage||'';const pageUtility=projectPage==='information'?'Projektinformation':projectPage==='reports'?'Rapporter':projectPage==='settings'?'Inställningar':'';const nativeControlPlan=Boolean(document.querySelector('.studioShell.view-native-control-plan'));const graphicalPlan=Boolean(document.querySelector('.studioShell.view-graphical-plan'));const backup=Boolean(document.querySelector('.studioShell.view-backup'));const effectiveLabel=pageUtility||activeLabel;const utilityActive=utilityItems.some(item=>item.label===effectiveLabel);for(const button of Array.from(document.querySelectorAll<HTMLButtonElement>('.rail .projectUtilityRailButton')))button.classList.toggle('active',button.dataset.utilityLabel===effectiveLabel||(nativeControlPlan&&button.dataset.utilityLabel==='Kontrollplan')||(graphicalPlan&&button.dataset.utilityLabel==='Grafisk plan')||(backup&&button.dataset.utilityLabel==='Backup'));const workspace=document.querySelector<HTMLElement>('.projectWorkspace');workspace?.classList.toggle('projectUtilityView',utilityActive)}")
s=s.replace("function openUtility(label:UtilityLabel,attempt=0){if(label==='Grafisk plan'){window.dispatchEvent(new CustomEvent('byggplan:open-graphical-plan'));return}if(label==='Kontrollplan'){window.dispatchEvent(new CustomEvent('byggplan:open-control-plan'));return}if(label==='Backup'){window.dispatchEvent(new CustomEvent('byggplan:open-backup'));return}hideNativeUtilityRows();const row=findRow(label);if(row){row.click();window.setTimeout(syncActive,30);return}const projectButton=document.querySelector<HTMLButtonElement>('.rail button[title=\"Projekt\"]');if(projectButton&&!document.querySelector('.projectWorkspace'))projectButton.click();if(attempt<30)window.setTimeout(()=>openUtility(label,attempt+1),50)}",
"function openUtility(label:UtilityLabel,attempt=0){if(label==='Grafisk plan'){window.dispatchEvent(new CustomEvent('byggplan:open-graphical-plan'));return}if(label==='Kontrollplan'){window.dispatchEvent(new CustomEvent('byggplan:open-control-plan'));return}if(label==='Backup'){window.dispatchEvent(new CustomEvent('byggplan:open-backup'));return}if(label==='Projektinformation'){window.dispatchEvent(new CustomEvent('byggplan:open-project-information'));return}if(label==='Rapporter'){window.dispatchEvent(new CustomEvent('byggplan:open-project-reports'));return}if(label==='Inställningar'){window.dispatchEvent(new CustomEvent('byggplan:open-project-settings'));return}hideNativeUtilityRows();const row=findRow(label);if(row){row.click();window.setTimeout(syncActive,30);return}const projectButton=document.querySelector<HTMLButtonElement>('.rail button[title=\"Projekt\"]');if(projectButton&&!document.querySelector('.projectWorkspace'))projectButton.click();if(attempt<30)window.setTimeout(()=>openUtility(label,attempt+1),50)}")
p.write_text(s)

# 3) StudioShell: listen for utility navigation, expose active page, and render reports mount in new architecture.
p=Path('studio/src/StudioShell.tsx')
s=p.read_text()
old="useEffect(()=>{const openUsers=()=>{if(!kaOnly)setView('users')};const openControlPlan=()=>setView('control-plan');const openGraphicalPlan=()=>{if(!kaOnly)setView('graphical-plan')};const openBackup=()=>{if(!kaOnly)setView('backup')};const openSystem=()=>{if(!kaOnly&&isSystemAdmin)setView('system-workspaces')};window.addEventListener('byggplan:open-users',openUsers);window.addEventListener('byggplan:open-control-plan',openControlPlan);window.addEventListener('byggplan:open-graphical-plan',openGraphicalPlan);window.addEventListener('byggplan:open-backup',openBackup);window.addEventListener('byggplan:open-system',openSystem);return()=>{window.removeEventListener('byggplan:open-users',openUsers);window.removeEventListener('byggplan:open-control-plan',openControlPlan);window.removeEventListener('byggplan:open-graphical-plan',openGraphicalPlan);window.removeEventListener('byggplan:open-backup',openBackup);window.removeEventListener('byggplan:open-system',openSystem)}},[kaOnly]);"
new="useEffect(()=>{const openUsers=()=>{if(!kaOnly)setView('users')};const openControlPlan=()=>setView('control-plan');const openGraphicalPlan=()=>{if(!kaOnly)setView('graphical-plan')};const openBackup=()=>{if(!kaOnly)setView('backup')};const openSystem=()=>{if(!kaOnly&&isSystemAdmin)setView('system-workspaces')};const openProjectInformation=()=>{if(!kaOnly&&projectId){setProjectPage('information');setView('projects')}};const openProjectReports=()=>{if(!kaOnly&&projectId){setProjectPage('reports');setView('projects')}};const openProjectSettings=()=>{if(!kaOnly&&projectId){setProjectPage('settings');setView('projects')}};window.addEventListener('byggplan:open-users',openUsers);window.addEventListener('byggplan:open-control-plan',openControlPlan);window.addEventListener('byggplan:open-graphical-plan',openGraphicalPlan);window.addEventListener('byggplan:open-backup',openBackup);window.addEventListener('byggplan:open-system',openSystem);window.addEventListener('byggplan:open-project-information',openProjectInformation);window.addEventListener('byggplan:open-project-reports',openProjectReports);window.addEventListener('byggplan:open-project-settings',openProjectSettings);return()=>{window.removeEventListener('byggplan:open-users',openUsers);window.removeEventListener('byggplan:open-control-plan',openControlPlan);window.removeEventListener('byggplan:open-graphical-plan',openGraphicalPlan);window.removeEventListener('byggplan:open-backup',openBackup);window.removeEventListener('byggplan:open-system',openSystem);window.removeEventListener('byggplan:open-project-information',openProjectInformation);window.removeEventListener('byggplan:open-project-reports',openProjectReports);window.removeEventListener('byggplan:open-project-settings',openProjectSettings)}},[kaOnly,isSystemAdmin,projectId]);"
if old not in s: raise SystemExit('StudioShell listener marker missing')
s=s.replace(old,new,1)
s=s.replace("return <div className={`studioShell view-control-plan ${projectsView?", "return <div data-project-page={projectsView?projectPage:undefined} className={`studioShell view-control-plan ${projectsView?",1)
s=s.replace("title=\"Projekt\" onClick={()=>setView('projects')}", "title=\"Projekt\" onClick={()=>{setProjectPage('overview');setView('projects')}}",1)
# mount reports hub alongside the new projects view
needle="</section></div></div>\n}"
repl="</section>{projectsView&&projectId&&projectPage==='reports'&&<ProjectReportsMount projectId={projectId}/>}</div></div>\n}"
if needle not in s: raise SystemExit('StudioShell closing marker missing')
s=s.replace(needle,repl,1)
p.write_text(s)

# 4) Portal mounts must also work in the embedded ProjectsView layout.
for filename in ['ProjectInformationMount.tsx','SystemBackupSettingsMount.tsx','ProjectExecutionResetSettingsMount.tsx']:
 p=Path('studio/src')/filename
 s=p.read_text()
 s=s.replace("const workspace=document.querySelector('.projectWorkspace') as HTMLElement|null;\n   const select=workspace?.querySelector('.topbar select') as HTMLSelectElement|null;\n   const page=workspace?.querySelector('.projectMain .projectPage') as HTMLElement|null;",
             "const workspace=document.querySelector('.projectWorkspace') as HTMLElement|null;\n   const select=(workspace?.querySelector('.topbar select')||document.querySelector('.controlPlanTopbar select')) as HTMLSelectElement|null;\n   const page=(workspace?.querySelector('.projectMain .projectPage')||document.querySelector('.projectsLandingMain .projectMain .projectPage')) as HTMLElement|null;")
 s=s.replace("const workspace=document.querySelector('.projectWorkspace') as HTMLElement|null;\n   const page=workspace?.querySelector('.projectMain .projectPage') as HTMLElement|null;",
             "const workspace=document.querySelector('.projectWorkspace') as HTMLElement|null;\n   const page=(workspace?.querySelector('.projectMain .projectPage')||document.querySelector('.projectsLandingMain .projectMain .projectPage')) as HTMLElement|null;")
 s=s.replace("if(!workspace||!page||!isInformation||!nextId)", "if(!page||!isInformation||!nextId)")
 s=s.replace("if(!workspace||!page||!isSettings)", "if(!page||!isSettings)")
 s=s.replace("if(!workspace||!page||!isSettings||!danger)", "if(!page||!isSettings||!danger)")
 p.write_text(s)

# 5) Reports mount itself must find embedded report page/main.
p=Path('studio/src/ProjectReportsMount.tsx')
s=p.read_text()
s=s.replace("const workspace=document.querySelector('.projectWorkspace') as HTMLElement|null;const main=workspace?.querySelector('.projectMain') as HTMLElement|null;", "const workspace=document.querySelector('.projectWorkspace') as HTMLElement|null;const main=(workspace?.querySelector('.projectMain')||document.querySelector('.projectsLandingMain .projectMain')) as HTMLElement|null;")
s=s.replace("const select=workspace?.querySelector('.topbar select') as HTMLSelectElement|null;", "const select=(workspace?.querySelector('.topbar select')||document.querySelector('.controlPlanTopbar select')) as HTMLSelectElement|null;")
p.write_text(s)
