import {useEffect,useState,type ReactNode} from 'react';
import './auth-gate.css';

type User={id:string;email:string;displayName:string;globalRoles:string[];projects:Array<{id:string;name:string;roles:string[]}>};
type Status={configured:boolean;bootstrapReady:boolean};

export function AuthGate({children}:{children:ReactNode}){
 const[status,setStatus]=useState<Status|null>(null),[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const sr=await fetch('/api/auth/status',{cache:'no-store'});if(!sr.ok)throw new Error('Kunde inte läsa inloggningsstatus.');const s=await sr.json() as Status;setStatus(s);if(!s.configured){setUser(null);return}const mr=await fetch('/api/auth/me',{cache:'no-store'});if(mr.ok){const m=await mr.json() as {user:User};setUser(m.user)}else setUser(null)}catch(e){setError(e instanceof Error?e.message:'Kunde inte läsa inloggningen.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 if(loading)return <div className="authCenter"><div className="authCard"><b>ByggPlan Studio</b><p>Kontrollerar inloggning…</p></div></div>;
 if(error)return <div className="authCenter"><div className="authCard"><h1>ByggPlan Studio</h1><p className="authError">{error}</p><button onClick={()=>void load()}>Försök igen</button></div></div>;
 if(status&&!status.configured&&status.bootstrapReady)return <Bootstrap onDone={u=>{setUser(u);setStatus({...status,configured:true})}}/>;
 if(status&&!status.configured&&!status.bootstrapReady)return <>{children}<div className="authDevNotice">Inloggning ej aktiverad ännu</div></>;
 if(!user)return <Login onDone={setUser}/>;
 return <>{children}<div className="authUserBadge"><span><b>{user.displayName}</b><small>{user.email}</small></span><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null)}}>Logga ut</button></div></>;
}

function Login({onDone}:{onDone:(user:User)=>void}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:any){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const x=await r.json().catch(()=>({})) as {user?:User;error?:string};if(!r.ok||!x.user)throw new Error(x.error||'Inloggningen misslyckades.');onDone(x.user)}catch(e){setError(e instanceof Error?e.message:'Inloggningen misslyckades.')}finally{setBusy(false)}}return <div className="authCenter"><form className="authCard" onSubmit={submit}><div className="authLogo">BP</div><small>BYGGPLAN STUDIO</small><h1>Logga in</h1><label>E-post<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Lösenord<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="authError">{error}</p>}<button disabled={busy}>{busy?'Loggar in…':'Logga in'}</button></form></div>}

function Bootstrap({onDone}:{onDone:(user:User)=>void}){const[token,setToken]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:any){e.preventDefault();if(password!==confirm){setError('Lösenorden är inte lika.');return}setBusy(true);setError('');try{const r=await fetch('/api/auth/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bootstrapToken:token,password})});const x=await r.json().catch(()=>({})) as {user?:User;error?:string};if(!r.ok||!x.user)throw new Error(x.error||'Kunde inte aktivera inloggningen.');onDone(x.user)}catch(e){setError(e instanceof Error?e.message:'Kunde inte aktivera inloggningen.')}finally{setBusy(false)}}return <div className="authCenter"><form className="authCard" onSubmit={submit}><div className="authLogo">BP</div><small>FÖRSTA INSTALLATION</small><h1>Aktivera inloggning</h1><p>Skapa lösenord för det befintliga administratörskontot. Bootstrapnyckeln är Cloudflare-hemligheten du anger en gång.</p><label>Bootstrapnyckel<input type="password" value={token} onChange={e=>setToken(e.target.value)} required/></label><label>Nytt lösenord<input type="password" autoComplete="new-password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Upprepa lösenord<input type="password" autoComplete="new-password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<p className="authError">{error}</p>}<button disabled={busy}>{busy?'Aktiverar…':'Aktivera inloggning'}</button></form></div>}
