import {useEffect,useMemo,useState} from 'react';
import {ReportApproval} from './ReportApproval';
import {ReportApprovalAction} from './ReportApprovalAction';
import './control-plan-review.css';

type Doc={id:string;title:string;document_type?:string;issuer?:string;reference?:string;item_count:number};
type Item={id:string;code?:string;description:string;section_code?:string;section_title?:string;responsible_role?:string;evidence_required?:string;handling_status?:string};
type Link={documentId:string;itemId:string};
type Meta={activity_id:string;applicability?:string;governing_documents?:Link[]};
type Entry={id:string;valueText?:string;valueNumber?:number;valueBoolean?:boolean;originalName?:string;createdAt?:string};
type Field={id:string;type:string;label:string;helpText?:string;required?:boolean;entries?:Entry[]};
type Activity={id:string;title:string;done:boolean;documentationFields?:Field[]};
type Task={activities:Activity[]};
type Evidence={activityId:string;done:boolean;fields:Field[]};

type SectionGroup={key:string;code:string;title:string;items:Item[]};

export function ControlPlanReviewView({projectId}:{projectId:string}){
 const[docs,setDocs]=useState<Doc[]>([]),[selected,setSelected]=useState(''),[items,setItems]=useState<Item[]>([]),[meta,setMeta]=useState<Meta[]>([]),[activities,setActivities]=useState<Map<string,Activity>>(new Map()),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[approvalVersion,setApprovalVersion]=useState(0);
 async function load(){setLoading(true);setMessage('');try{const[dr,mr,tr]=await Promise.all([fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/governing-documents`,{cache:'no-store'}),fetch(`/api/project-field-metadata?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'}),fetch(`/api/tasks?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'})]);if(!dr.ok)throw new Error('Kunde inte läsa kontrollplanen.');const dd=await dr.json() as {documents?:Doc[]};const controlDocs=(dd.documents||[]).filter(d=>/kontrollplan/i.test(`${d.title} ${d.document_type||''}`)&&Number(d.item_count||0)>0);setDocs(controlDocs);setSelected(cur=>controlDocs.some(d=>d.id===cur)?cur:(controlDocs[0]?.id||''));const md=mr.ok?await mr.json() as {items?:Meta[]}:{items:[]};setMeta(md.items||[]);const td=tr.ok?await tr.json() as {tasks?:Task[]}:{tasks:[]};const am=new Map<string,Activity>();for(const task of td.tasks||[])for(const a of task.activities||[])am.set(a.id,a);setActivities(am)}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa kontrollplanen.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[projectId]);
 useEffect(()=>{if(!selected){setItems([]);return}void(async()=>{const r=await fetch(`/api/studio/governing-documents/${encodeURIComponent(selected)}`,{cache:'no-store'});if(!r.ok){setMessage('Kunde inte läsa kontrollpunkterna.');return}const x=await r.json() as {items?:Item[]};setItems(x.items||[])})()},[selected]);
 useEffect(()=>{const changed=()=>void load();window.addEventListener('byggplan:activity-status-changed',changed);return()=>window.removeEventListener('byggplan:activity-status-changed',changed)},[projectId]);
 const evidenceByItem=useMemo(()=>{const map=new Map<string,Evidence[]>();for(const m of meta){if(m.applicability==='deprecated')continue;const a=activities.get(m.activity_id);if(!a)continue;for(const link of m.governing_documents||[]){if(link.documentId!==selected||!link.itemId)continue;const list=map.get(link.itemId)||[];list.push({activityId:a.id,done:Boolean(a.done),fields:a.documentationFields||[]});map.set(link.itemId,list)}}return map},[meta,activities,selected]);
 const groups=useMemo<SectionGroup[]>(()=>{const map=new Map<string,SectionGroup>();for(const item of items){const code=String(item.section_code||'').trim();const title=String(item.section_title||'Övriga kontrollpunkter').trim();const key=`${code}|${title}`;const group=map.get(key)||{key,code,title,items:[]};group.items.push(item);map.set(key,group)}return [...map.values()]},[items]);
 const currentDoc=docs.find(d=>d.id===selected);
 const completeCount=items.filter(item=>{const ev=evidenceByItem.get(item.id)||[];return ev.length>0&&ev.every(x=>x.done)}).length;
 return <div className="controlPlanReview projectPage"><div className="pageHero"><small>KONTROLLPLAN</small><h1>Kontroll och attest</h1><p>Kontrollpunkter, underlag och attest i en vy för byggherre och kontrollansvarig.</p></div>{message&&<div className="reportMessage">{message}</div>}{loading?<div className="workspaceEmpty">Laddar kontrollplan…</div>:docs.length===0?<div className="infoCard">Ingen kontrollplan med kontrollpunkter hittades bland projektets styrdokument.</div>:<div className="cpReviewLayout"><aside className="cpReviewDocs">{docs.map(d=><button key={d.id} className={selected===d.id?'selected':''} onClick={()=>setSelected(d.id)}><b>{d.title}</b><small>{d.reference||d.issuer||`${d.item_count} punkter`}</small></button>)}</aside><main className="cpReviewMain"><header className="cpReviewHeader"><div><small>KONTROLLPLAN</small><h2>{currentDoc?.title}</h2><p>{[currentDoc?.reference,currentDoc?.issuer].filter(Boolean).join(' · ')}</p></div><div><b>{completeCount}/{items.length}</b><span> kontrollpunkter färdiga</span></div></header><div className="cpReviewSections">{groups.map(group=><section className="cpReviewSection" key={group.key}><header className="cpReviewSectionHeader">{group.code&&<span>{group.code}</span>}<div><h2>{group.title}</h2><small>{group.items.length} kontrollpunkt{group.items.length===1?'':'er'}</small></div></header><div className="cpReviewItems">{group.items.map(item=>{const evidence=evidenceByItem.get(item.id)||[],ready=evidence.length>0&&evidence.every(x=>x.done);const fields=evidence.flatMap(x=>x.fields).filter(f=>(f.entries||[]).length>0);return <article key={item.id} className={ready?'ready':''}><div className="cpPointState">{ready?'✓':'○'}</div><div className="cpPointBody"><div className="cpPointTitle"><span>{item.code||'•'}</span><div><h3>{item.description}</h3></div></div><div className="cpPointMeta">{item.responsible_role&&<span>Ansvar <b>{item.responsible_role}</b></span>}{item.evidence_required&&<span>Förväntat underlag <b>{item.evidence_required}</b></span>}</div><section className="cpEvidence"><small>UNDERLAG</small>{fields.length?fields.map(f=><div className="cpEvidenceField" key={f.id}><b>{f.label}</b>{f.helpText&&<small>{f.helpText}</small>}<div>{(f.entries||[]).map(e=><span key={e.id}>{e.originalName||e.valueText||(e.valueNumber!==undefined?String(e.valueNumber):e.valueBoolean!==undefined?(e.valueBoolean?'Ja':'Nej'):'Dokumenterat')}</span>)}</div></div>):<p>{ready?'Punkten är klarmarkerad men saknar registrerat underlag i dokumentationsfälten.':'Underlag visas här när den kopplade kontrollen dokumenterats och klarmarkerats.'}</p>}</section></div><aside className="cpAttestation"><ReportApproval key={`${item.id}-${approvalVersion}`} projectId={projectId} itemId={item.id}/><ReportApprovalAction projectId={projectId} itemId={item.id} responsibleRole={item.responsible_role} onDone={()=>setApprovalVersion(v=>v+1)}/></aside></article>})}</div></section>)}</div></main></div>}</div>
}
