import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';

type DocumentSummary={id:string;title:string;document_type:string;source_filename:string};
type VersionRow={id:string;version_no:number;version_label:string;status:string;original_name:string;size_bytes:number;note?:string;created_at:string;activated_at?:string|null};

export function GoverningDocumentVersionAction({projectId}:{projectId:string}){
 const[target,setTarget]=useState<Element|null>(null),[documents,setDocuments]=useState<DocumentSummary[]>([]),[selectedTitle,setSelectedTitle]=useState('');
 const[open,setOpen]=useState(false),[versions,setVersions]=useState<VersionRow[]>([]),[file,setFile]=useState<File|null>(null),[versionLabel,setVersionLabel]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{void loadDocuments()},[projectId]);
 useEffect(()=>{const sync=()=>{const header=document.querySelector('.governingPrimaryView .governingPageHeader');setTarget(current=>current===header?current:header);setSelectedTitle(header?.querySelector('h1')?.textContent?.trim()||'')};sync();const timer=window.setInterval(sync,250);return()=>window.clearInterval(timer)},[]);
 const selected=useMemo(()=>documents.find(d=>d.title===selectedTitle)||null,[documents,selectedTitle]);
 async function loadDocuments(){try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/governing-documents`,{cache:'no-store'});const d=await r.json().catch(()=>({})) as {documents?:DocumentSummary[]};if(r.ok)setDocuments(d.documents||[])}catch{}}
 async function loadVersions(documentId:string){setBusy(true);setMessage('');try{const r=await fetch(`/api/studio/governing-documents/${encodeURIComponent(documentId)}/versions`,{cache:'no-store'});const d=await r.json().catch(()=>({})) as {versions?:VersionRow[];error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte läsa versionshistoriken.');setVersions(d.versions||[])}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa versionshistoriken.')}finally{setBusy(false)}}
 function show(){if(!selected)return;setOpen(true);setFile(null);setVersionLabel('');setNote('');setMessage('');void loadVersions(selected.id)}
 function close(){if(busy)return;setOpen(false);setFile(null);setVersionLabel('');setNote('');setMessage('')}
 async function upload(){if(!selected||!file||busy)return;setBusy(true);setMessage('Laddar upp ny version som kandidat…');try{if(file.size>25*1024*1024)throw new Error('Filen får vara högst 25 MB.');const form=new FormData();form.append('file',file,file.name);form.append('versionLabel',versionLabel.trim());form.append('note',note.trim());const r=await fetch(`/api/studio/governing-documents/${encodeURIComponent(selected.id)}/version-candidates`,{method:'POST',body:form});const d=await r.json().catch(()=>({})) as {error?:string;candidate?:{versionLabel?:string}};if(!r.ok)throw new Error(d.error||'Kunde inte spara kandidatversionen.');setMessage(`${d.candidate?.versionLabel||'Den nya versionen'} är sparad som kandidat. Ingenting i projektet eller befintliga aktiviteter har ändrats.`);setFile(null);setVersionLabel('');setNote('');await loadVersions(selected.id)}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara kandidatversionen.')}finally{setBusy(false)}}
 async function removeCandidate(version:VersionRow){if(!selected||busy||version.status!=='candidate')return;if(!window.confirm(`Ta bort kandidatversionen ”${version.version_label}”? Den aktiva versionen påverkas inte.`))return;setBusy(true);try{const r=await fetch(`/api/studio/governing-documents/${encodeURIComponent(selected.id)}/version-candidates/${encodeURIComponent(version.id)}`,{method:'DELETE'});const d=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte ta bort kandidatversionen.');setMessage('Kandidatversionen togs bort.');await loadVersions(selected.id)}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte ta bort kandidatversionen.')}finally{setBusy(false)}}
 if(!target||!selected)return null;
 return createPortal(<><div className="governingVersionAction"><button onClick={show}>↻ Uppdatera version</button></div>{open&&<div className="governingImportModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="governingImportModal governingVersionModal"><div className="governingImportModalHeader"><div><small>VERSIONSHANTERING</small><h2>Uppdatera {selected.title}</h2></div><button disabled={busy} onClick={close}>×</button></div><div className="governingVersionSafety"><b>Säker uppdatering</b><span>Den nya filen sparas först som kandidat. Nuvarande styrpunkter, aktivitetskopplingar, klarmarkeringar och dokumentation lämnas orörda tills skillnaderna har granskats.</span></div>{message&&<div className="projectSupportMessage">{message}</div>}<div className="projectSupportForm"><label><span>Versionsnamn</span><input value={versionLabel} onChange={e=>setVersionLabel(e.target.value)} placeholder={`Ex. Version ${Math.max(2,...versions.map(v=>v.version_no+1))}`}/></label><label><span>Kommentar</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ex. Ny kontrollplan efter tekniskt samråd"/></label><label className="projectSupportUpload"><input type="file" accept="image/*,application/pdf,.pdf" onChange={e=>{const f=e.target.files?.[0]||null;e.target.value='';setFile(f)}}/><span>{file?`📎 ${file.name}`:'＋ Välj ny PDF eller bild'}</span></label><div className="governingVersionUploadActions"><button disabled={busy} onClick={close}>Stäng</button><button className="primary" disabled={busy||!file} onClick={()=>void upload()}>{busy?'Arbetar…':'Ladda upp som kandidat'}</button></div></div><section className="governingVersionHistory"><h3>Versionshistorik</h3>{versions.length===0?<p>Ingen versionshistorik ännu.</p>:versions.map(v=><article key={v.id} className={v.status}><div><b>{v.version_label||`Version ${v.version_no}`}</b><small>{v.original_name} · {formatDate(v.created_at)}</small>{v.note&&<span>{v.note}</span>}</div><em>{v.status==='active'?'Aktiv':v.status==='candidate'?'Kandidat':'Historik'}</em>{v.status==='candidate'&&<button disabled={busy} onClick={()=>void removeCandidate(v)}>Ta bort kandidat</button>}</article>)}</section><div className="governingVersionNext"><b>Nästa steg efter uppladdning</b><p>Den nya versionen ska jämföras mot den aktiva: oförändrade punkter behålls, nya kan läggas till, medan ändrade eller borttagna punkter ska kräva ett uttryckligt beslut. Ingen aktivitet ska tas bort automatiskt.</p></div></div></div>}</>,target);
}
function formatDate(value:string){const d=new Date(value.includes('T')?value:`${value.replace(' ','T')}Z`);return Number.isNaN(d.getTime())?value:d.toLocaleString('sv-SE',{dateStyle:'short',timeStyle:'short'})}
