import { useEffect,useState } from 'react';

type GoverningFile={originalName:string;contentType:string;sizeBytes:number;url:string};
type GoverningDocument={id:string;document_type:string;title:string;issuer:string;reference:string;status:string;imported_at:string;file?:GoverningFile|null};

const documentTypes=[
  ['control_plan','Kontrollplan'],
  ['authority_decision','Myndighetsbeslut / tillstånd'],
  ['building_permit','Bygglov'],
  ['technical_consultation','Tekniskt samråd'],
  ['work_environment','Arbetsmiljö'],
  ['other','Annat styrdokument']
] as const;

export function GoverningDocumentsEditor({projectId}:{projectId:string}){
  const[documents,setDocuments]=useState<GoverningDocument[]>([]);const[loading,setLoading]=useState(true);const[editing,setEditing]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  const[documentType,setDocumentType]=useState('control_plan');const[title,setTitle]=useState('');const[issuer,setIssuer]=useState('');const[reference,setReference]=useState('');const[file,setFile]=useState<File|null>(null);
  useEffect(()=>{void load()},[projectId]);
  async function load(){setLoading(true);setMessage('');try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/governing-document-files`,{cache:'no-store'});const raw=await r.text();let d:{documents?:GoverningDocument[];error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||'Kunde inte läsa styrdokument.');setDocuments(d.documents||[]);}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa styrdokument.');}finally{setLoading(false)}}
  function start(){setEditing(true);setDocumentType('control_plan');setTitle('');setIssuer('');setReference('');setFile(null);setMessage('')}
  function cancel(){setEditing(false);setTitle('');setIssuer('');setReference('');setFile(null)}
  async function save(){if(!title.trim()||!file)return;setBusy(true);setMessage('Importerar styrdokument…');try{if(file.size>25*1024*1024)throw new Error('Filen får vara högst 25 MB.');const form=new FormData();form.append('projectId',projectId);form.append('documentType',documentType);form.append('title',title.trim());form.append('issuer',issuer.trim());form.append('reference',reference.trim());form.append('file',file,file.name);const r=await fetch('/api/studio/governing-document-files/import',{method:'POST',body:form});const raw=await r.text();if(raw.toLowerCase().includes('forsakringskassan.se/errorpage'))throw new Error('Nätverksfiltret blockerar filuppladdningen från detta nät.');let d:{error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||`Importen misslyckades (HTTP ${r.status}).`);cancel();await load();setMessage('Styrdokumentet är importerat. Originalfilen är sparad.');window.setTimeout(()=>setMessage(''),2500);}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte importera styrdokumentet.');}finally{setBusy(false)}}
  async function remove(item:GoverningDocument){if(!confirm(`Ta bort styrdokumentet ”${item.title}”?`))return;setMessage('Tar bort…');const r=await fetch(`/api/studio/governing-document-files/${encodeURIComponent(item.id)}`,{method:'DELETE'});if(r.ok){await load();setMessage('Styrdokumentet är borttaget.');window.setTimeout(()=>setMessage(''),1800)}else setMessage('Kunde inte ta bort styrdokumentet.')}
  return <section className="projectDocumentsEditor governingDocumentsEditor"><div className="projectDocumentsHeader"><div><small>STYRDOKUMENT</small><h2>Krav och kontroller för projektet</h2><p>Kontrollplaner, myndighetsbeslut, tillstånd och andra dokument som styr vad som ska göras eller kontrolleras.</p></div><button className="primary" onClick={start}>＋ Importera styrdokument</button></div>{message&&<div className="projectSupportMessage">{message}</div>}{loading&&<div className="projectSupportEmpty">Laddar styrdokument…</div>}{!loading&&editing&&<div className="projectSupportForm"><label><span>Dokumenttyp</span><select value={documentType} onChange={e=>setDocumentType(e.target.value)}>{documentTypes.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label><span>Rubrik</span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Kontrollplan inför tekniskt samråd"/></label><label><span>Utfärdare</span><input value={issuer} onChange={e=>setIssuer(e.target.value)} placeholder="Ex. Kontrollansvarig eller Härjedalens kommun"/></label><label><span>Referens / diarienummer</span><input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Valfritt"/></label><label className="projectSupportUpload"><input type="file" accept="image/*,application/pdf,.pdf" onChange={e=>{const selected=e.target.files?.[0]||null;e.target.value='';setFile(selected)}}/><span>{file?`📎 ${file.name}`:'＋ Välj PDF eller bild'}</span></label><div><button onClick={cancel} disabled={busy}>Avbryt</button><button className="primary" disabled={busy||!title.trim()||!file} onClick={()=>void save()}>{busy?'Importerar…':'Importera'}</button></div></div>}{!loading&&!editing&&documents.map(item=><article className="projectSupportCard" key={item.id}><div className="projectSupportCardMain"><strong>{item.title}</strong><p>{typeLabel(item.document_type)}{item.issuer?` · ${item.issuer}`:''}</p>{item.file&&<div className="projectSupportAttachments"><div className="projectSupportAttachment"><a href={item.file.url} target="_blank" rel="noreferrer"><span>{item.file.contentType.startsWith('image/')?'🖼':'📄'}</span><span><b>{item.file.originalName}</b><small>{formatBytes(item.file.sizeBytes)}</small></span></a></div></div>}<small>Tolkning av kontrollpunkter kopplas till dokumentet i nästa steg.</small></div><div className="projectSupportCardActions"><button className="danger" onClick={()=>void remove(item)}>Ta bort</button></div></article>)}{!loading&&!editing&&!documents.length&&<div className="projectSupportEmpty">Inga styrdokument har importerats ännu.</div>}</section>
}
function typeLabel(value:string){return documentTypes.find(([key])=>key===value)?.[1]||'Styrdokument'}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${Math.round(value/1024)} kB`;return `${(value/(1024*1024)).toFixed(1)} MB`}
