import {useState} from 'react';

type Activity={id:string;title:string;activity_type:string;task_title:string;section_name:string;area_name:string;done?:number;score?:number};
type DraftItem={id?:string;code?:string;description?:string;section_title?:string};
type DecisionRow={key:string;kind:'added'|'changed'|'removed';oldItem?:DraftItem|null;newItem?:DraftItem|null;existingActivities:Activity[];suggestions:Activity[];recommendation:string;decision:{action:string;selectedActivityIds:string[];comment:string}};
type Plan={summary:{changed:number;added:number;removed:number};decisions:DecisionRow[]};

const LABELS:Record<string,string>={
 defer:'Bestäm senare',link_existing:'Koppla till befintlig aktivitet',create_activity:'Skapa ny aktivitet',update_keep_links:'Uppdatera styrpunkten – behåll befintliga kopplingar',review_links:'Uppdatera efter granskning av kopplingar',keep_old:'Behåll gamla styrpunkten tills vidare',keep_historical:'Behåll historiskt – ändra inte aktiviteter',unlink_only:'Koppla bort styrpunkten men behåll aktiviteter'
};
const ACTIONS:Record<string,string[]>={added:['defer','link_existing','create_activity'],changed:['update_keep_links','review_links','keep_old','defer'],removed:['keep_historical','unlink_only','defer']};

export function GoverningVersionDecisionList({documentId,versionId}:{documentId:string;versionId:string}){
 const[open,setOpen]=useState(false),[plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(){setOpen(true);setBusy(true);setMessage('Tar fram beslutsförslag…');try{const r=await fetch(`/api/studio/governing-documents/${encodeURIComponent(documentId)}/version-candidates/${encodeURIComponent(versionId)}/decision-plan`,{cache:'no-store'});const d=await r.json().catch(()=>({})) as Plan&{error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte skapa beslutslistan.');setPlan(d);setMessage('Beslutslistan är ett förslag. Inga projektdata ändras när du sparar besluten.')}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte skapa beslutslistan.')}finally{setBusy(false)}}
 function patch(key:string,update:Partial<DecisionRow['decision']>){setPlan(current=>current?{...current,decisions:current.decisions.map(row=>row.key===key?{...row,decision:{...row.decision,...update}}:row)}:current)}
 async function save(row:DecisionRow){setBusy(true);setMessage(`Sparar beslut för ${row.newItem?.code||row.oldItem?.code||'styrpunkten'}…`);try{const r=await fetch(`/api/studio/governing-documents/${encodeURIComponent(documentId)}/version-candidates/${encodeURIComponent(versionId)}/decisions/${encodeURIComponent(row.key)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(row.decision)});const d=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte spara beslutet.');setMessage('Beslutet är sparat som underlag. Ingen aktivitet eller styrpunkt har ändrats ännu.')}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara beslutet.')}finally{setBusy(false)}}
 if(!open)return <div className="governingDecisionLaunch"><button className="primary" onClick={()=>void load()}>Öppna beslutslista</button><span>Bestäm hur nya, ändrade och borttagna styrpunkter ska hanteras innan versionen aktiveras.</span></div>;
 return <section className="governingDecisionList"><div className="governingDecisionHeader"><div><small>NÄSTA STEG</small><h3>Beslutslista för versionsbytet</h3></div><button disabled={busy} onClick={()=>setOpen(false)}>Dölj</button></div>{plan&&<div className="governingDecisionSummary"><span>{plan.summary.added} nya</span><span>{plan.summary.changed} ändrade</span><span>{plan.summary.removed} borttagna</span></div>}{message&&<div className="projectSupportMessage">{message}</div>}{plan?.decisions.length===0?<p>Det finns inga ändringar som kräver beslut.</p>:plan?.decisions.map(row=><article key={row.key} className={`decision-${row.kind}`}><div className="governingDecisionTitle"><span>{row.kind==='added'?'Ny':row.kind==='changed'?'Ändrad':'Borttagen'}</span><b>{row.newItem?.code||row.oldItem?.code} {row.newItem?.description||row.oldItem?.description}</b></div><p className="governingDecisionRecommendation">{row.recommendation}</p>{row.existingActivities.length>0&&<div className="governingDecisionExisting"><small>Befintliga kopplingar</small>{row.existingActivities.map(a=><span key={a.id}>{a.done?'✓ ':''}{a.title}<em>{a.task_title}</em></span>)}</div>}{row.kind==='added'&&row.suggestions.length>0&&<div className="governingDecisionSuggestions"><small>Föreslagna befintliga aktiviteter</small>{row.suggestions.map((a,index)=><label key={a.id}><input type="checkbox" checked={row.decision.selectedActivityIds.includes(a.id)} onChange={e=>patch(row.key,{selectedActivityIds:e.target.checked?[...new Set([...row.decision.selectedActivityIds,a.id])]:row.decision.selectedActivityIds.filter(id=>id!==a.id),action:e.target.checked?'link_existing':row.decision.action})}/><span><b>{index===0?'Förslag: ':''}{a.title}</b><em>{a.area_name} › {a.section_name} › {a.task_title}</em></span></label>)}</div>}<label className="governingDecisionAction"><span>Beslut</span><select value={row.decision.action} onChange={e=>patch(row.key,{action:e.target.value})}>{ACTIONS[row.kind].map(action=><option key={action} value={action}>{LABELS[action]}</option>)}</select></label><label className="governingDecisionComment"><span>Kommentar</span><input value={row.decision.comment} onChange={e=>patch(row.key,{comment:e.target.value})} placeholder="Valfri notering om beslutet"/></label><div className="governingDecisionSave"><button disabled={busy} onClick={()=>void save(row)}>Spara beslut</button></div></article>) }<div className="governingVersionSafety"><b>Fortfarande säkert läge</b><span>Besluten lagras bara som migrationsunderlag. Ingen aktivitet skapas, tas bort, kopplas om eller ändrar status i detta steg.</span></div></section>;
}
