export const VK4410_ENVIRONMENT_DECISION = {
  documentType: 'authority_decision',
  title: 'Tillstånd för enskild avloppsanläggning – Vemdalens Kyrkby 44:10',
  issuer: 'Berg och Härjedalens miljö- och byggnämnd',
  reference: 'm-2026-617 · 2026-06-04',
  sourceFilename: 'Enskilt avlopp - Tillstånd - Infiltration_Håkan_Tunell_197204157916_074c605d.pdf',
  sourceMimeType: 'application/pdf',
  items: [
    { code: 'A-01', sectionCode: 'A', sectionTitle: 'Tillstånd och giltighet', itemType: 'administration', responsibleRole:'BH', description: 'Tillståndet upphör att gälla om arbetet inte påbörjas inom 2 år och avslutas inom 5 år från beslutsdatum 2026-06-04.', evidenceRequired: 'Datum för påbörjande och färdigställande' },
    { code: 'A-02', sectionCode: 'A', sectionTitle: 'Tillstånd och omfattning', itemType: 'condition', responsibleRole:'BH/EK', description: 'Anläggningen ska bestå av slamavskiljare med våtvolym 3 m³ för upp till 5 personer med efterföljande rening i den befintliga gemensamma förstärkta infiltrationen.', evidenceRequired: 'Produkt- och installationsdokumentation' },

    { code: 'V-01', sectionCode: 'V', sectionTitle: 'Villkor vid anläggandet', itemType: 'condition', responsibleRole:'EK', description: 'Anläggningen ska placeras och utföras enligt ansökan, inkomna kompletteringar och tillverkarens anvisningar om inte beslutets villkor anger annat.', evidenceRequired: 'Utförande och relevant dokumentation' },
    { code: 'V-02', sectionCode: 'V', sectionTitle: 'Villkor vid anläggandet', itemType: 'condition', responsibleRole:'Fackkunnig/entreprenör', description: 'Installationen ska utföras av dokumenterat sakkunnig person på ett fackmannamässigt sätt.', evidenceRequired: 'Uppgift om utförare / entreprenörsrapport' },
    { code: 'V-03', sectionCode: 'V', sectionTitle: 'Villkor vid anläggandet', itemType: 'measurement', responsibleRole:'EK', description: 'Avståndet mellan infiltrationsnivån och grundvattenytan ska normalt vara minst 1 m och får aldrig understiga 0,5 m.', evidenceRequired: 'Mått eller kommentar om varför posten inte kan verifieras' },
    { code: 'V-04', sectionCode: 'V', sectionTitle: 'Villkor vid anläggandet', itemType: 'control', responsibleRole:'EK', description: 'Avloppsanläggningen ska vara tät fram till infiltrationen och infiltrationen ska hållas fri från växtlighet med grova rötter.', evidenceRequired: 'Kontroll / dokumentation' },
    { code: 'V-05', sectionCode: 'V', sectionTitle: 'Villkor vid anläggandet', itemType: 'condition', responsibleRole:'EK', description: 'Dag- och dräneringsvatten, backspolningsvatten, pool- och badtunnevatten samt andra i beslutet angivna främmande vatten får inte ledas till avloppsanläggningen.', evidenceRequired: 'Kontroll av anslutningar' },
    { code: 'V-06', sectionCode: 'V', sectionTitle: 'Villkor vid anläggandet', itemType: 'administration', responsibleRole:'BH', description: 'Snarast efter färdigställandet ska ifylld entreprenörsrapport och fotodokumentation skickas till miljö- och byggnämnden.', evidenceRequired: 'Entreprenörsrapport + insänd fotodokumentation' },

    { code: 'FUNK-01', sectionCode: 'FUNK', sectionTitle: 'Funktionskrav', itemType: 'condition', responsibleRole:'BH', description: 'Avloppsanläggningen ska förväntas reducera totalfosfor med minst 70 procent och organiska ämnen BOD7 eller BOD5 med minst 90 procent.', evidenceRequired: 'Godkänd anläggningslösning / produktunderlag' },
    { code: 'FUNK-02', sectionCode: 'FUNK', sectionTitle: 'Funktionskrav', itemType: 'condition', responsibleRole:'BH', description: 'Utsläppet får inte medverka till väsentligt ökad risk för smitta, lukt eller annan olägenhet där människor kan exponeras.', evidenceRequired: 'Drift och funktion utan noterad olägenhet' },

    { code: 'D-01', sectionCode: 'D', sectionTitle: 'Skötsel och drift', itemType: 'information', responsibleRole:'BH', description: 'Anläggningen ska kontrolleras och skötas enligt ansökan, kompletteringar och tillverkarens anvisningar.', evidenceRequired: 'Drift- och skötselinformation' },
    { code: 'D-02', sectionCode: 'D', sectionTitle: 'Skötsel och drift', itemType: 'administration', responsibleRole:'BH', description: 'Anläggningen ska slamtömmas enligt tillverkarens anvisningar och så ofta som tillverkaren anger, dock minst en gång per år.', evidenceRequired: 'Slamtömningsrutin / utförd tömning' },
    { code: 'D-03', sectionCode: 'D', sectionTitle: 'Skötsel och drift', itemType: 'control', responsibleRole:'BH', description: 'Anläggningen ska vara åtkomlig för slamtömning och får inte täckas över eller på annat sätt göras oåtkomlig.', evidenceRequired: 'Översikt / åtkomlighet för slamtömning' },
    { code: 'D-04', sectionCode: 'D', sectionTitle: 'Skötsel och dokumentation', itemType: 'administration', responsibleRole:'BH', description: 'Tillståndet med villkor ska finnas tillgängligt hos sökanden och överlämnas till ny ägare vid överlåtelse av fastigheten.', evidenceRequired: 'Beslut bevarat / överlämnat' },
    { code: 'D-05', sectionCode: 'D', sectionTitle: 'Skötsel och dokumentation', itemType: 'information', responsibleRole:'BH', description: 'Större ingrepp, materialbyte eller andra åtgärder av betydelse för anläggningens funktion kan kräva anmälan till miljö- och byggnämnden.', evidenceRequired: 'Kontakta nämnden vid framtida ändring' },
    { code: 'D-06', sectionCode: 'D', sectionTitle: 'Skötsel och drift', itemType: 'administration', responsibleRole:'BH', description: 'Fastighetsägaren ansvarar för att sköta och underhålla anläggningen samt se till att slamtömning är genomförbar och att vägen och uppställningsplatsen uppfyller renhållningsbolagets krav.', evidenceRequired: 'Driftrutin och åtkomlighet' },

    { code: 'M-01', sectionCode: 'M', sectionTitle: 'Markarbete', itemType: 'condition', responsibleRole:'BH/EK', description: 'Om en fornlämning påträffas under grävning eller annat arbete ska arbetet avbrytas och länsstyrelsen kontaktas.', evidenceRequired: 'Åtgärd endast om fornlämning påträffas' },

    { code: 'F-01', sectionCode: 'F', sectionTitle: 'Fotodokumentation enligt bilaga 2', itemType: 'documentation', responsibleRole:'EK', description: 'Ta en bild i varje installerad brunn, exempelvis slambrunn, fördelningsbrunn och eventuell uppsamlingsbrunn.', evidenceRequired: 'Foto i varje installerad brunn' },
    { code: 'F-02', sectionCode: 'F', sectionTitle: 'Fotodokumentation enligt bilaga 2', itemType: 'documentation', responsibleRole:'EK', description: 'Ta bild på infiltration eller markbädd när gropen är grävd och tom så att markmaterial längs väggar och botten syns.', evidenceRequired: 'Foto av tom grop och markmaterial / hantering som ej tillämplig för befintlig infiltration' },
    { code: 'F-03', sectionCode: 'F', sectionTitle: 'Fotodokumentation enligt bilaga 2', itemType: 'documentation', responsibleRole:'EK', description: 'Ta ytterligare en bild per utförd del av infiltrationen eller markbädden så att varje lager av sand, grus och spridningsledningar syns.', evidenceRequired: 'Foto av varje lager / hantering som ej tillämplig för befintlig infiltration' },
    { code: 'F-04', sectionCode: 'F', sectionTitle: 'Fotodokumentation enligt bilaga 2', itemType: 'documentation', responsibleRole:'EK', description: 'Ta bild på ledningarna innan de läggs igen.', evidenceRequired: 'Foto av ledningar före återfyllning' },
    { code: 'F-05', sectionCode: 'F', sectionTitle: 'Fotodokumentation enligt bilaga 2', itemType: 'documentation', responsibleRole:'EK', description: 'Ta en översiktsbild som visar brunnens placering, infiltrationens eller markbäddens placering och huset.', evidenceRequired: 'Översiktsfoto' },
    { code: 'F-06', sectionCode: 'F', sectionTitle: 'Fotodokumentation enligt bilaga 2', itemType: 'administration', responsibleRole:'BH', description: 'Skicka bilderna tillsammans med entreprenörsrapporten till miljö- och byggnämnden så snart avloppet är anlagt.', evidenceRequired: 'Insänd fotodokumentation + entreprenörsrapport' }
  ]
} as const;
