import { useEffect,useMemo,useState } from 'react';

type Area={id:string;project_id:string;name:string;sort_order?:number};
type Section={id:string;work_area_id:string;name:string;sort_order?:number};
type Task={id:string;work_section_id:string;title:string;description?:string;status?:string;sort_order?:number};
type Activity={id:string;task_id:string;title:string;description?:string;activity_type:string;required?:number;sort_order?:number};
type Structure={areas:Area[];sections:Section[];tasks:Task[];activities:Activity[]};
type Props={projectId:string;projectName?:string};
type PlanNode={task:Task;area:Area;section:Section;activities:Activity[];stop:boolean;status:'done'|'active'|'planned'};

const EMPTY:Structure={areas:[],sections:[],tasks:[],activities:[]};
const STOP_WORDS=/kontroll|besikt|inspektion|godkänn|startbesked|slutbesked|samråd|utsättning|lägeskontroll|provtryck/i;

function order<T extends {sort_order?:number;name?:string;title?:string}>(items:T[]){return [...items].sort((a,b)=>(a.sort_order??999999)-(b.sort_order??999999)||String(a.name||a.title||'').localeCompare(String(b.name||b.title||''),'sv'))}
function statusOf(task:Task):PlanNode['status']{const value=String(task.status||'').toLowerCase();if(['done','completed','complete','closed','klar','finished'].includes(value))return'done';if(['active','in_progress','in-progress','started','pågår','ongoing'].includes(value))return'active';return'planned'}
function isStop(task:Task,activities:Activity[]){return activities.some(a=>['approval','control','check','measurement'].includes(String(a.activity_type||'').toLowerCase()))||STOP_WORDS.test(task.title)}

export function GraphicalPlanView({projectId,projectName}:Props){
 const[structure,setStructure]=useState<Structure>(EMPTY);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[selected,setSelected]=useState<string>('');
 useEffect(()=>{let cancelled=false;async function load(){setLoading(true);setError('');try{const r=await fetch(`/api/studio/structure?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'});if(!r.ok)throw new Error('Kunde inte läsa projektplanen.');const data=await r.json() as Structure;if(cancelled)return;setStructure(data);setSelected(cur=>cur&&data.tasks.some(t=>t.id===cur)?cur:data.tasks.find(t=>statusOf(t)==='active')?.id||data.tasks[0]?.id||'')}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'Kunde inte läsa projektplanen.')}finally{if(!cancelled)setLoading(false)}}if(projectId)void load();return()=>{cancelled=true}},[projectId]);
 const lanes=useMemo(()=>order(structure.areas).map(area=>({area,sections:order(structure.sections.filter(s=>s.work_area_id===area.id)).map(section=>({section,nodes:order(structure.tasks.filter(t=>t.work_section_id===section.id)).map(task=>{const activities=order(structure.activities.filter(a=>a.task_id===task.id));return{task,area,section,activities,stop:isStop(task,activities),status:statusOf(task)} as PlanNode})}))})).filter(l=>l.sections.some(s=>s.nodes.length)),[structure]);
 const allNodes=useMemo(()=>lanes.flatMap(l=>l.sections.flatMap(s=>s.nodes)),[lanes]);const selectedNode=allNodes.find(n=>n.task.id===selected)||allNodes[0];
 const done=allNodes.filter(n=>n.status==='done').length;const stops=allNodes.filter(n=>n.stop).length;
 if(loading)return <div className="graphPlanState">Hämtar grafisk plan…</div>;if(error)return <div className="graphPlanState error">{error}</div>;
 return <div className="graphPlanPage"><header className="graphPlanHeader"><div><small>GRAFISK PLAN</small><h1>{projectName||'Projektplan'}</h1><p>Grova moment och viktiga stoppunkter i projektets arbetsordning.</p></div><div className="graphPlanSummary"><span><b>{done}</b> klara</span><span><b>{allNodes.length-done}</b> kvar</span><span><b>{stops}</b> stoppunkter</span></div></header><div className="graphLegend"><span><i className="legendDot activity"/>Moment</span><span><i className="legendDot stop"/>Stoppunkt</span><span><i className="legendDot done">✓</i>Klar</span><span><i className="legendDot active"/>Pågår</span></div>{allNodes.length===0?<div className="graphPlanEmpty"><b>Planen är tom</b><span>Lägg först in moment i projektstrukturen.</span></div>:<div className="graphPlanLayout"><section className="graphCanvas" aria-label="Grafisk projektplan">{lanes.map(({area,sections})=><div className="graphArea" key={area.id}><div className="graphAreaTitle"><span>Arbetsområde</span><b>{area.name}</b></div>{sections.map(({section,nodes})=><div className="graphLane" key={section.id}><div className="graphLaneLabel"><small>ARBETSAVSNITT</small><strong>{section.name}</strong></div><div className="graphTrack">{nodes.map((node,index)=><div className="graphStepWrap" key={node.task.id}>{index>0&&<span className={`graphConnector ${node.status==='done'?'done':''}`}/>}<button className={`graphStep ${node.stop?'stop':''} ${node.status} ${selectedNode?.task.id===node.task.id?'selected':''}`} onClick={()=>setSelected(node.task.id)} title={node.task.title}><span className="graphNode">{node.status==='done'?'✓':node.stop?'!':''}</span><span className="graphNodeText"><b>{node.task.title}</b><small>{node.stop?'STOPPUNKT · ':''}{node.status==='done'?'Klar':node.status==='active'?'Pågår':'Planerad'}</small></span></button></div>)}</div></div>)}</div>)}</section>{selectedNode&&<aside className="graphInspector"><div className="graphInspectorTop"><span className={`graphInspectorNode ${selectedNode.stop?'stop':''} ${selectedNode.status}`}>{selectedNode.status==='done'?'✓':selectedNode.stop?'!':''}</span><div><small>{selectedNode.stop?'STOPPUNKT':'MOMENT'}</small><h2>{selectedNode.task.title}</h2><p>{selectedNode.status==='done'?'Klar':selectedNode.status==='active'?'Pågår':'Planerad'}</p></div></div><dl><div><dt>Arbetsområde</dt><dd>{selectedNode.area.name}</dd></div><div><dt>Arbetsavsnitt</dt><dd>{selectedNode.section.name}</dd></div><div><dt>Aktiviteter</dt><dd>{selectedNode.activities.length}</dd></div></dl>{selectedNode.task.description&&<div className="graphDescription"><small>BESKRIVNING</small><p>{selectedNode.task.description}</p></div>}{selectedNode.activities.length>0&&<div className="graphActivities"><small>AKTIVITETER I MOMENTET</small>{selectedNode.activities.map(a=><div key={a.id}><span>{['approval','control','check','measurement'].includes(a.activity_type)?'◆':'○'}</span><b>{a.title}</b></div>)}</div>}</aside>}</div>}</div>
}
