import React from 'react';
import ReactDOM from 'react-dom/client';
import './same-origin-api';
import './mapping-dialog-clarity';
import { installExecutionContextBridge } from './execution-context-bridge';
import { installProjectUtilityRail } from './project-utility-rail';
import { StudioShell } from './StudioShell';
import { MasterV2UpgradeAction } from './MasterV2UpgradeAction';
import { ProjectInformationMount } from './ProjectInformationMount';
import { AuthGate } from './AuthGate';
import './styles.css';
import './palette.css';
import './classifications.css';
import './control-plan.css';
import './governing-documents.css';
import './governing-verifications.css';
import './governing-verification-lock.css';
import './governing-mapping.css';
import './governing-mapping-exception.css';
import './mapping-dialog-clarity.css';
import './studio-shell.css';
import './master-projects.css';
import './project-support.css';
import './project-documents.css';
import './project-administration.css';
import './project-detail-tabs.css';
import './project-activities.css';
import './project-workspace-v2.css';
import './api-browser.css';
import './governing-import-action.css';
import './governing-analysis-action.css';
import './governing-workspace-nav.css';
import './governing-mapping-rail.css';
import './project-utility-rail.css';
import './graphical-plan.css';

installExecutionContextBridge();
installProjectUtilityRail();
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><AuthGate><StudioShell/><ProjectInformationMount/><MasterV2UpgradeAction/></AuthGate></React.StrictMode>);
