import {useEffect,useState,type FormEvent} from 'react';
import './project-users.css';

type Member={id:string;email:string;displayName:string;status:string;isProjectMember?:boolean;hasLogin:boolean;roles:string[];globalRoles?:string[]};
type Role={code:string;name:string};
const DEFAULT_ROLES=['KA'];

export function ProjectUsersView({projectId}:{projectId:string}){
 const[members,setMembers]=useState<Member[]>([]),[availableRoles,setAvailableRoles]=useState<Role[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[creating,setCreating]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/members`,{cache:'no-store'});const x=await r.json().catch(()=>({})) as {members?:Member[];availableRoles?:Role[];error?:string};if(!r.ok)throw new Error(x.error||'Kunde inte läsa användarna.');setMembers(x.members||[]);setAvailableRoles(x.availableRoles||[])}catch(e){setError(e instanceof Error?e.message:'Kunde inte läsa användarna.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[projectId]);
 return <div className="projectUsers projectPage"><div className="pageHero"><small>ANVÄNDARE</small><h1>Projektmedlemmar</h1><p>Samma användare kan ha globala systemroller och flera projektroller. BH och KA används även vid signering av kontrollplanen.</p></div><div className="projectUsersToolbar"><button onClick={()=>setCreating(true)}>+ Lägg till användare</button></div>{error&&<div className="usersMessage error">{error}</div>}{loading?<div className="workspaceEmpty">Hämtar användare…</div>:<div className="memberList">{members.map(m=><MemberCard key={m.id} member={m} roles={availableRoles} projectId={projectId} onSaved={load}/>)}</div>}{creating&&<CreateMember roles={availableRoles} projectId={projectId} onClose={()=>setCreating(false)} onSaved={async()=>{setCreating(false);await load()}}/>}</div>;
}

function roleLabel(code:string){return code==='BH'?'Byggherre':code==='KA'?'Kontrollansvarig':code==='worker'?'Arbetare':code==='supervisor'?'Arbetsledare':code==='admin'?'Administratör':code}
function MemberCard({member,roles,projectId,onSaved}:{member:Member;roles:Role[];projectId:string;onSaved:()=>Promise<void>}){const[editing,setEditing]=useState(false),[selected,setSelected]=useState<string[]>(member.roles),[password,setPassword]=useState(''),[name,setName]=useState(member.displayName),[busy,setBusy]=useState(false),[error,setError]=useState('');useEffect(()=>{setSelected(member.roles);setName(member.displayName)},[member.id,member.roles,member.displayName]);async function save(){setBusy(true);setError('');try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/members/${encodeURIComponent(member.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:name,roles:selected,password:password||undefined})});const x=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(x.error||'Kunde inte spara användaren.');setPassword('');setEditing(false);await onSaved()}catch(e){setError(e instanceof Error?e.message:'Kunde inte spara användaren.')}finally{setBusy(false)}}const globalRoles=member.globalRoles||[];return <article className="memberCard"><header><div className="memberAvatar">{member.displayName.slice(0,1).toUpperCase()}</div><div><h3>{member.displayName}</h3><p>{member.email}</p></div><span className={member.hasLogin?'loginReady':'loginMissing'}>{member.hasLogin?'Inloggning klar':'Saknar lösenord'}</span><button onClick={()=>setEditing(v=>!v)}>{editing?'Stäng':'Redigera'}</button></header>{globalRoles.length>0&&<div className="memberRoles">{globalRoles.map(r=><span key={`global-${r}`}>{roleLabel(r)} · systemroll</span>)}</div>}<div className="memberRoles">{member.roles.length?member.roles.map(r=><span key={r}>{roleLabel(r)}</span>):<em>{member.isProjectMember===false?'Ingen projektroll ännu':'Ingen projektroll'}</em>}</div>{editing&&<div className="memberEdit"><label>Namn<input value={name} onChange={e=>setName(e.target.value)}/></label><fieldset><legend>Projektroller</legend>{roles.map(role=><label key={role.code}><input type="checkbox" checked={selected.includes(role.code)} onChange={e=>setSelected(cur=>e.target.checked?[...cur,role.code]:cur.filter(x=>x!==role.code))}/><span><b>{role.name}</b><small>{role.code}</small></span></label>)}</fieldset>{member.isProjectMember===false&&<div className="usersMessage">När du sparar läggs användaren samtidigt till som medlem i det här projektet.</div>}<label>Nytt lösenord <small>(lämna tomt för att behålla befintligt)</small><input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder={member.hasLogin?'••••••••••':'Minst 10 tecken'}/></label>{error&&<div className="usersMessage error">{error}</div>}<div className="memberEditActions"><button disabled={busy} onClick={()=>void save()}>{busy?'Sparar…':'Spara'}</button></div></div>}</article>}

function CreateMember({roles,projectId,onClose,onSaved}:{roles:Role[];projectId:string;onClose:()=>void;onSaved:()=>Promise<void>}){const[email,setEmail]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState(''),[selected,setSelected]=useState<string[]>(DEFAULT_ROLES),[busy,setBusy]=useState(false),[error,setError]=useState('');async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/members`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,displayName:name,password,roles:selected})});const x=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(x.error||'Kunde inte skapa användaren.');await onSaved()}catch(e){setError(e instanceof Error?e.message:'Kunde inte skapa användaren.')}finally{setBusy(false)}}return <div className="memberDialogBackdrop"><form className="memberDialog" onSubmit={save}><header><div><small>NY PROJEKTMEDLEM</small><h2>Lägg till användare</h2></div><button type="button" onClick={onClose}>×</button></header><label>Namn<input autoFocus value={name} onChange={e=>setName(e.target.value)} required/></label><label>E-post<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Första lösenord<input type="password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/><small>Minst 10 tecken. Användaren kan logga in direkt efter att den skapats.</small></label><fieldset><legend>Projektroller</legend>{roles.map(role=><label key={role.code}><input type="checkbox" checked={selected.includes(role.code)} onChange={e=>setSelected(cur=>e.target.checked?[...cur,role.code]:cur.filter(x=>x!==role.code))}/><span><b>{role.name}</b><small>{role.code}</small></span></label>)}</fieldset>{error&&<div className="usersMessage error">{error}</div>}<footer><button type="button" className="secondary" onClick={onClose}>Avbryt</button><button disabled={busy}>{busy?'Skapar…':'Skapa användare'}</button></footer></form></div>}
