import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {ControlPlanReviewView} from './ControlPlanReviewView';

export function ProjectControlPlanMount({projectId}:{projectId:string}){
 const[target,setTarget]=useState<HTMLElement|null>(null);
 useEffect(()=>{let observer:MutationObserver|undefined;let cleanup:()=>void=()=>{};function wire(){cleanup();const tree=document.querySelector('.projectWorkspace .projectTree') as HTMLElement|null;const main=document.querySelector('.projectWorkspace .projectMain') as HTMLElement|null;if(!tree||!main)return;let row=tree.querySelector('[data-project-control-plan]') as HTMLElement|null;if(!row){row=document.createElement('div');row.className='projectTreeRow projectControlPlanNav';row.setAttribute('data-project-control-plan','true');row.style.paddingLeft='10px';row.innerHTML='<span class="navSpacer"></span><span>📋</span><span class="projectTreeLabel">Kontrollplan</span>';const nativeRows=Array.from(tree.querySelectorAll(':scope > .projectTreeRow, :scope > div > .projectTreeRow')) as HTMLElement[];const reports=nativeRows.find(r=>r.querySelector('.projectTreeLabel')?.textContent?.trim()==='Rapporter');if(reports){const holder=reports.parentElement===tree?reports:reports.parentElement;tree.insertBefore(row,holder||reports)}else tree.appendChild(row)}const open=()=>{for(const child of Array.from(main.children) as HTMLElement[])child.style.display='none';row!.classList.add('selected');main.classList.add('controlPlanMainOpen');main.scrollTop=0;setTarget(main)};const close=()=>{row!.classList.remove('selected');main.classList.remove('controlPlanMainOpen');setTarget(null);for(const child of Array.from(main.children) as HTMLElement[])child.style.display=''};row.addEventListener('click',open);const others=Array.from(tree.querySelectorAll('.projectTreeRow')).filter(x=>x!==row) as HTMLElement[];for(const other of others)other.addEventListener('click',close);cleanup=()=>{row?.removeEventListener('click',open);for(const other of others)other.removeEventListener('click',close);main.classList.remove('controlPlanMainOpen')}}wire();observer=new MutationObserver(()=>{if(!document.querySelector('[data-project-control-plan]'))wire()});observer.observe(document.body,{childList:true,subtree:true});return()=>{observer?.disconnect();cleanup();setTarget(null)}},[projectId]);
 if(!target)return null;
 return createPortal(<ControlPlanReviewView projectId={projectId}/>,target);
}
