import { useEffect,useMemo,useState } from 'react';

type Condition={id:string;code:string;title?:string;description:string;section_code:string;section_title:string;item_type:string;governing_document_id:string;governing_document_title:string;document_type:string;issuer:string;reference:string;condition_kind?:string;source_type?:string};
type Activity={id:string;title:string;task_id:string};type Task={id:string;title:string;work_section_id:string};type Section={id:string;name:string;work_area_id:string};type Area={id:string;name:string};

export function ProjectConditionsView({projectId}:{projectId:string}){
 const[items,setItems]=useState<Condition[]>([]);const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);const[adding,setAdding]=useState(false);const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[activities,setActivities]=useState<Activity[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[sections,setSections]=useState<Section[]>([]);const[areas,setAreas]=useState<Area[]>([]);const[selectedActivity,setSelectedActivity]=useState('');const[converting,setConverting]=useState(false);
 async function load(){setLoading(true);setMessage('');try{const[r,sr]=await Promise.all([fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/project-conditions`,{cache:'no-store'}),fetch(`/api/studio/structure?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'})]);const d=await r.json().catch(()=>({})) as {conditions?:Condition[];error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte läsa projektvillkor.');setItems(d.conditions||[]);if(sr.ok){const s=await sr.json() as {activities?:Activity[];tasks?:Task[];sections?:Section[];areas?:Area[]};setActivities(s.activities||[]);setTasks(s.tasks||[]);setSections(s.sections||[]);setAreas(s.areas||[])}}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa projektvillkor.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[projectId]);
 const groups=useMemo(()=>{const m=new Map<string,{title:string;items:Condition[]}>();for(const item of items){const key=item.governing_document_id||item.governing_document_title||item.source_type||'project';const g=m.get(key)||{title:item.governing_document_title||'Projektspecifikt',items:[]};g.items.push(item);m.set(key,g)}return [...m.values()]},[items]);
 const activityOptions=useMemo(()=>activities.map(activity=>{const task=tasks.find(t=>t.id===activity.task_id);const section=sections.find(s=>s.id===task?.work_section_id);const area=areas.find(a=>a.id===section?.work_area_id);return{id:activity.id,label:[area?.name,section?.name,task?.title,activity.title].filter(Boolean).join(' › ')}}).sort((a,b)=>a.label.localeCompare(b.label,'sv')),[activities,tasks,sections,areas]);
 async function add(){if(!title.trim())return;setAdding(true);try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/project-conditions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.trim(),description:description.trim()})});const d=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte skapa projektvillkoret.');setTitle('');setDescription('');await load()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte skapa projektvillkoret.')}finally{setAdding(false)}}
 async function convert(){if(!selectedActivity)return;const option=activityOptions.find(x=>x.id===selectedActivity);if(!window.confirm(`Flytta ”${option?.label||'aktiviteten'}” till Projektvillkor? Aktiviteten pensioneras i arbetsflödet.`))return;setConverting(true);setMessage('');try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/project-conditions/from-activity/${encodeURIComponent(selectedActivity)}`,{method:'POST'});const d=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte flytta aktiviteten.');setSelectedActivity('');await load();setMessage('Aktiviteten flyttades till Projektvillkor och pensionerades i arbetsflödet.')}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte flytta aktiviteten.')}finally{setConverting(false)}}
 return <section className="projectConditions projectTabContent"><div className="projectTabHeader"><div><small>PROJEKTVILLKOR</small><h2>Stående instruktioner och villkor</h2><p>Krav som gäller fortlöpande under projektet och därför inte ska bockas av som vanliga aktiviteter.</p></div></div>
 {message&&<div className="projectSupportMessage">{message}</div>}
 <div className="projectConditionTools"><div className="projectConditionAdd"><h3>＋ Lägg till projektspecifikt villkor</h3><label><span>Rubrik</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Fuktskydda material och konstruktion under byggtid"/></label><label><span>Instruktion</span><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Beskriv vad som ska gälla under projektet…"/></label><button className="primary" disabled={adding||!title.trim()} onClick={()=>void add()}>{adding?'Sparar…':'Lägg till villkor'}</button></div>
 <div className="projectConditionConvert"><h3>↪ Flytta befintlig aktivitet hit</h3><p>För sådant som ligger som aktivitet men egentligen är en stående instruktion under hela projektet.</p><select value={selectedActivity} onChange={e=>setSelectedActivity(e.target.value)}><option value="">Välj aktivitet…</option>{activityOptions.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select><button disabled={converting||!selectedActivity} onClick={()=>void convert()}>{converting?'Flyttar…':'Flytta till Projektvillkor'}</button></div></div>
 {loading?<div className="projectSupportEmpty">Laddar projektvillkor…</div>:!items.length?<div className="projectSupportEmpty">Inga projektvillkor är registrerade ännu.</div>:<div className="projectConditionGroups">{groups.map(group=><section key={group.title} className="projectConditionGroup"><h3>{group.title}</h3>{group.items.map(item=><article key={`${item.condition_kind||''}:${item.id}`} className="projectConditionItem"><small>{[item.section_code,item.section_title,item.code].filter(Boolean).join(' · ')||'Projektspecifikt villkor'}</small>{item.title&&item.title!==item.description&&<strong>{item.title}</strong>}<p>{item.description||item.title}</p></article>)}</section>)}</div>}
 </section>;
}
