import { useEffect,useMemo,useState } from 'react';
import { ProjectSupportEditor } from './ProjectSupportEditor';

type DocumentationEntry={id:string;valueText?:string;valueNumber?:number;valueBoolean?:boolean;originalName?:string;createdAt:string};
type DocumentationField={id:string;type:'photo'|'number'|'text'|'boolean'|'file'|'choice'|'signature';label:string;helpText?:string;unit?:string;required:boolean;minimumItems?:number;entries:DocumentationEntry[];options?:string[]};
type Activity={id:string;title:string;description?:string;type:string;done:boolean;required:boolean;documentationFields:DocumentationField[]};
type Task={id:string;workArea:string;workSection:string;title:string;status:string;activities:Activity[]};
type Meta={activity_id:string;context?:string;surface?:string;applicability?:string;lifecycle_stage?:string;governing_documents?:any[]};
type FlatActivity=Activity&{taskId:string;taskTitle:string;workArea:string;workSection:string;taskStatus:string;meta?:Meta};
const TYPE_LABELS:Record<string,string>={perform:'Utför',document:'Dokumentera',measurement:'Mät',check:'Kontrollera',approval:'Godkänn',note:'Anteckna',choice:'Välj'};

export function ProjectActivitiesView({projectId,focusActivityId='',detailOnly=false}:{projectId:string;focusActivityId?:string;detailOnly?:boolean}){
 const[tasks,setTasks]=useState<Task[]>([]);const[meta,setMeta]=useState<Map<string,Meta>>(new Map());const[selected,setSelected]=useState<string>(focusActivityId);const[query,setQuery]=useState('');const[status,setStatus]=useState<'all'|'todo'|'done'>('all');const[place,setPlace]=useState<'all'|'studio'|'field'>('all');const[loading,setLoading]=useState(true);const[message,setMessage]=useState('');
 async function load(){setLoading(true);setMessage('');try{const[tr,mr]=await Promise.all([fetch(`/api/tasks?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'}),fetch(`/api/project-field-metadata?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'})]);if(!tr.ok)throw new Error('Kunde inte läsa aktiviteter.');const td=await tr.json() as {tasks?:Task[]};setTasks(td.tasks||[]);if(mr.ok){const md=await mr.json() as {items?:Meta[]};setMeta(new Map((md.items||[]).map(x=>[x.activity_id,x])))}else setMeta(new Map())}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa aktiviteter.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[projectId]);useEffect(()=>{if(focusActivityId)setSelected(focusActivityId)},[focusActivityId]);
 const all=useMemo<FlatActivity[]>(()=>tasks.flatMap(task=>task.activities.map(a=>({...a,taskId:task.id,taskTitle:task.title,workArea:task.workArea,workSection:task.workSection,taskStatus:task.status,meta:meta.get(a.id)}))).filter(a=>a.meta?.applicability!=='deprecated'),[tasks,meta]);
 const filtered=useMemo(()=>all.filter(a=>{if(status==='done'&&!a.done)return false;if(status==='todo'&&a.done)return false;const studio=a.meta?.surface==='studio'||a.meta?.context==='administrative';if(place==='studio'&&!studio)return false;if(place==='field'&&studio)return false;const hay=`${a.title} ${a.description||''} ${a.workArea} ${a.workSection} ${a.taskTitle}`.toLocaleLowerCase('sv-SE');return !query.trim()||hay.includes(query.trim().toLocaleLowerCase('sv-SE'))}),[all,status,place,query]);
 const current=all.find(a=>a.id===selected)||null;
 async function setDone(a:FlatActivity){try{const r=await fetch(`/api/activities/${encodeURIComponent(a.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({done:!a.done})});if(!r.ok){const d=await r.json().catch(()=>({})) as {error?:string};throw new Error(d.error||'Kunde inte uppdatera status.')}await load()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte uppdatera status.')}}
 if(detailOnly)return <div className="projectActivities detailOnly">{message&&<div className="projectSupportMessage">{message}</div>}{loading?<div className="projectSupportEmpty">Laddar aktivitet…</div>:current?<><div className="activityQuickStatus"><button className={current.done?'done':''} onClick={()=>void setDone(current)}>{current.done?'✓ Klar':'○ Markera klar'}</button></div><ActivityDetail activity={current} reload={load} setMessage={setMessage}/></>:<div className="projectSupportEmpty">Aktiviteten kunde inte läsas.</div>}</div>;
 return <div className="projectActivities"><div className="projectTabHeader"><div><small>AKTIVITETER</small><h2>Alla projektaktiviteter</h2><p>Studio visar hela projektets aktivitetsflöde. Fält/Studio anger normal arbetsyta men begränsar inte var aktiviteten får hanteras.</p></div></div><div className="activityToolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Sök aktivitet, moment eller arbetsområde…"/><select value={status} onChange={e=>setStatus(e.target.value as any)}><option value="all">Alla statusar</option><option value="todo">Att göra</option><option value="done">Klara</option></select><select value={place} onChange={e=>setPlace(e.target.value as any)}><option value="all">Alla arbetsytor</option><option value="studio">Studio</option><option value="field">Fält</option></select><button onClick={()=>void load()}>↻ Uppdatera</button></div>{message&&<div className="projectSupportMessage">{message}</div>}<div className="activityStats"><b>{filtered.length}</b><span>visas av {all.length} aktiva aktiviteter</span><span>{all.filter(a=>a.done).length} klara</span></div>{loading?<div className="projectSupportEmpty">Laddar aktiviteter…</div>:<div className="activitiesLayout"><div className="activitiesList">{filtered.map(a=>{const studio=a.meta?.surface==='studio'||a.meta?.context==='administrative';return <article key={a.id} className={`${a.done?'done':''} ${selected===a.id?'selected':''}`} onClick={()=>setSelected(a.id)}><button className="activityDone" title={a.done?'Markera som inte klar':'Markera klar'} onClick={e=>{e.stopPropagation();void setDone(a)}}>{a.done?'✓':'○'}</button><div><b>{a.title}</b><small>{a.workArea} › {a.workSection} › {a.taskTitle}</small></div><span className="activityType">{TYPE_LABELS[a.type]||a.type}</span><span className={`activityPlace ${studio?'studio':'field'}`}>{studio?'Studio':'Fält'}</span></article>})}{filtered.length===0&&<div className="projectSupportEmpty">Inga aktiviteter matchar filtret.</div>}</div><div className="activityDetail">{current?<ActivityDetail activity={current} reload={load} setMessage={setMessage}/>:<div className="projectSupportEmpty">Välj en aktivitet för att visa och redigera den.</div>}</div></div>}</div>
}
function ActivityDetail({activity,reload,setMessage}:{activity:FlatActivity;reload:()=>Promise<void>;setMessage:(s:string)=>void}){const[title,setTitle]=useState(activity.title);const[description,setDescription]=useState(activity.description||'');const[type,setType]=useState(activity.type);const[busy,setBusy]=useState(false);useEffect(()=>{setTitle(activity.title);setDescription(activity.description||'');setType(activity.type)},[activity.id,activity.title,activity.description,activity.type]);async function save(){setBusy(true);try{const map:Record<string,string>={perform:'work',document:'documentation',measurement:'measurement',check:'control',approval:'approval',note:'wait',choice:'wait'};const r=await fetch(`/api/studio/activities/${encodeURIComponent(activity.id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.trim(),description,activityType:map[type]||type})});if(!r.ok){const d=await r.json().catch(()=>({})) as {error?:string};throw new Error(d.error||'Kunde inte spara aktiviteten.')}setMessage('Aktiviteten sparad');await reload()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara aktiviteten.')}finally{setBusy(false)}}return <><section className="activityEditor"><small>AKTIVITET</small><h3>{activity.title}</h3><p className="activityPath">{activity.workArea} › {activity.workSection} › {activity.taskTitle}</p><label><span>Rubrik</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>Beskrivning / instruktion</span><textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><label><span>Aktivitetstyp</span><select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(TYPE_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><div className="activityMeta"><span>Status: <b>{activity.done?'Klar':'Att göra'}</b></span><span>Normal arbetsyta: <b>{activity.meta?.surface==='studio'||activity.meta?.context==='administrative'?'Studio':'Fält'}</b></span><span>Styrdokument: <b>{activity.meta?.governing_documents?.length||0}</b></span></div><button className="primary" disabled={busy||!title.trim()} onClick={()=>void save()}>{busy?'Sparar…':'Spara ändringar'}</button></section><DocumentationFields fields={activity.documentationFields||[]} reload={reload} setMessage={setMessage}/><ProjectSupportEditor ownerType="activity" ownerId={activity.id}/></>}
function DocumentationFields({fields,reload,setMessage}:{fields:DocumentationField[];reload:()=>Promise<void>;setMessage:(s:string)=>void}){if(!fields.length)return <section className="activityDocs"><small>DOKUMENTATION</small><p>Aktiviteten har inga särskilda dokumentationsfält.</p></section>;async function put(field:DocumentationField,payload:any){const r=await fetch(`/api/documentation-fields/${field.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw new Error('Dokumentationen kunde inte sparas.');await reload()}async function upload(field:DocumentationField,file:File){const form=new FormData();form.append('file',file,file.name);const r=await fetch(`/api/documentation-fields/${field.id}/files`,{method:'POST',body:form});if(!r.ok)throw new Error('Filen kunde inte laddas upp.');await reload()}return <section className="activityDocs"><small>DOKUMENTATION</small><h3>Dokumentationskrav</h3>{fields.map(f=><div className="docField" key={f.id}><label><span>{f.label}{f.required?' *':''}</span>{f.helpText&&<small>{f.helpText}</small>}{(f.type==='photo'||f.type==='file'||f.type==='signature')?<input type="file" accept={f.type==='photo'?'image/*':undefined} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(f,file).catch(err=>setMessage(err.message))}}/>:f.type==='number'?<input type="number" defaultValue={f.entries?.[0]?.valueNumber??''} onBlur={e=>void put(f,{valueNumber:e.target.value===''?null:Number(e.target.value)}).catch(err=>setMessage(err.message))}/>:f.type==='boolean'?<input type="checkbox" defaultChecked={Boolean(f.entries?.[0]?.valueBoolean)} onChange={e=>void put(f,{valueBoolean:e.target.checked}).catch(err=>setMessage(err.message))}/>:f.type==='choice'?<select defaultValue={f.entries?.[0]?.valueText||''} onChange={e=>void put(f,{valueText:e.target.value}).catch(err=>setMessage(err.message))}><option value="">Välj…</option>{(f.options||[]).map(o=><option key={o}>{o}</option>)}</select>:<input defaultValue={f.entries?.[0]?.valueText||''} onBlur={e=>void put(f,{valueText:e.target.value}).catch(err=>setMessage(err.message))}/>}</label>{f.entries?.length>0&&<div className="docEntries">{f.entries.map(e=><span key={e.id}>{e.originalName||e.valueText||e.valueNumber?.toString()||(e.valueBoolean?'Ja':'')}</span>)}</div>}</div>)}</section>}
