import { useEffect,useState } from 'react';

type Attachment={id:string;originalName:string;contentType:string;sizeBytes:number;url:string};
type ProjectDocument={id:string;title:string;description:string;attachments:Attachment[]};

export function ProjectDocumentsEditor({projectId}:{projectId:string}){
  const[documents,setDocuments]=useState<ProjectDocument[]>([]);const[loading,setLoading]=useState(true);const[editingId,setEditingId]=useState('');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[busy,setBusy]=useState(false);const[bulkBusy,setBulkBusy]=useState(false);const[message,setMessage]=useState('');const[pendingFile,setPendingFile]=useState<File|null>(null);const[editMode,setEditMode]=useState(false);const[openingId,setOpeningId]=useState('');
  useEffect(()=>{void load()},[projectId]);
  useEffect(()=>{const workspace=document.querySelector('.projectWorkspace');if(!workspace)return;const sync=()=>{const next=workspace.classList.contains('editMode');setEditMode(next);if(!next)setEditingId('')};sync();const observer=new MutationObserver(sync);observer.observe(workspace,{attributes:true,attributeFilter:['class']});return()=>observer.disconnect()},[]);
  async function load(){setLoading(true);setMessage('');try{const r=await fetch(`/api/project-documents?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'});const raw=await r.text();let d:{documents?:ProjectDocument[];error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||'Kunde inte läsa projektdokument.');setDocuments(d.documents||[]);}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa projektdokument.');}finally{setLoading(false)}}
  function newItem(){setEditingId('new');setTitle('');setDescription('');setPendingFile(null);setMessage('');}
  function edit(item:ProjectDocument){setEditingId(item.id);setTitle(item.title);setDescription(item.description||'');setPendingFile(null);setMessage('');}
  function cancel(){setEditingId('');setTitle('');setDescription('');setPendingFile(null);}
  async function uploadById(documentId:string,file:File){if(file.size>20*1024*1024)throw new Error('Filen får vara högst 20 MB.');const form=new FormData();form.append('file',file,file.name);const r=await fetch(`/api/studio/project-document-files/${encodeURIComponent(documentId)}`,{method:'POST',body:form});const raw=await r.text();if(raw.toLowerCase().includes('forsakringskassan.se/errorpage'))throw new Error('Nätverksfiltret blockerar filuppladdning till ByggPlan från detta nät.');let d:{error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||'Kunde inte ladda upp filen.');}
  async function createDocument(titleValue:string,descriptionValue=''){const r=await fetch('/api/studio/project-documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,title:titleValue,description:descriptionValue})});const raw=await r.text();let d:{id?:string;error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok||!d.id)throw new Error(d.error||raw||`Kunde inte skapa projektdokumentet (HTTP ${r.status}).`);return d.id;}
  async function addFiles(files:File[]){if(!files.length)return;setBulkBusy(true);setMessage(`Lägger till ${files.length} dokument…`);let created=0;const failed:string[]=[];for(const file of files){let documentId='';try{if(file.size>20*1024*1024)throw new Error('Filen är större än 20 MB.');documentId=await createDocument(filenameTitle(file.name));await uploadById(documentId,file);created+=1;}catch(e){failed.push(`${file.name}: ${e instanceof Error?e.message:'kunde inte läggas till'}`);if(documentId)await fetch(`/api/studio/project-documents/${encodeURIComponent(documentId)}`,{method:'DELETE'}).catch(()=>{});}}await load();if(failed.length)setMessage(`${created} dokument lades till. ${failed.length} misslyckades: ${failed.join(' · ')}`);else{setMessage(`${created} projektdokument lades till.`);window.setTimeout(()=>setMessage(''),2200)}setBulkBusy(false);}
  async function save(){if(!title.trim())return;setBusy(true);setMessage('Sparar…');try{const isNew=editingId==='new';let documentId=editingId;if(isNew)documentId=await createDocument(title.trim(),description);else{const r=await fetch(`/api/studio/project-documents/${editingId}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.trim(),description})});const raw=await r.text();let d:{error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||`Kunde inte spara projektdokumentet (HTTP ${r.status}).`);}if(isNew&&pendingFile&&documentId){setMessage('Dokumentet sparat. Laddar upp fil…');await uploadById(documentId,pendingFile);}cancel();await load();setMessage('Projektdokumentet är sparat.');window.setTimeout(()=>setMessage(''),1800);}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara projektdokumentet.');}finally{setBusy(false)}}
  async function openFile(file:Attachment){setOpeningId(file.id);setMessage('');const tab=window.open('','_blank');try{const r=await fetch(file.url,{cache:'no-store'});if(!r.ok){const raw=await r.text().catch(()=> '');throw new Error(raw||`Kunde inte öppna filen (HTTP ${r.status}).`)}const blob=await r.blob();const objectUrl=URL.createObjectURL(blob);if(tab){tab.location.href=objectUrl}else{const a=document.createElement('a');a.href=objectUrl;a.target='_blank';a.rel='noreferrer';a.click()}window.setTimeout(()=>URL.revokeObjectURL(objectUrl),60000);}catch(e){tab?.close();setMessage(e instanceof Error?e.message:'Kunde inte öppna filen.');}finally{setOpeningId('')}}
  async function remove(item:ProjectDocument){if(!confirm(`Ta bort projektdokumentet ”${item.title}”?`))return;const r=await fetch(`/api/studio/project-documents/${encodeURIComponent(item.id)}`,{method:'DELETE'});if(r.ok)await load();}
  return <section className={`projectDocumentsEditor ${editMode?'documentsEditMode':'documentsWorkMode'}`}><div className="projectDocumentsHeader"><div><small>PROJEKTDOKUMENT</small><h2>Dokument för hela projektet</h2><p>{editMode?'Redigera rubriker och ta bort dokument.':'Öppna projektets dokument eller lägg till nya filer.'}</p></div><div className="projectDocumentsHeaderActions"><label className={`primary projectDocumentsBulkUpload ${bulkBusy?'busy':''}`}><input type="file" multiple accept="image/*,application/pdf,.pdf" disabled={bulkBusy} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';if(files.length)void addFiles(files)}}/><span>{bulkBusy?'Lägger till…':'＋ Lägg till dokument'}</span></label>{editMode&&<button onClick={newItem} disabled={bulkBusy}>＋ Nytt utan fil</button>}</div></div>{message&&<div className="projectSupportMessage">{message}</div>}{loading&&<div className="projectSupportEmpty">Laddar projektdokument…</div>}{!loading&&editMode&&editingId&&<div className="projectSupportForm"><label><span>Rubrik</span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Bygglov"/></label><label><span>Beskrivning</span><textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Valfri beskrivning…"/></label>{editingId==='new'&&<label className="projectSupportUpload"><input type="file" accept="image/*,application/pdf,.pdf" onChange={e=>{const file=e.target.files?.[0]||null;e.target.value='';setPendingFile(file);if(file&&!title.trim())setTitle(filenameTitle(file.name))}}/><span>{pendingFile?`📎 ${pendingFile.name}`:'＋ Välj bild eller PDF'}</span></label>}<div><button onClick={cancel} disabled={busy}>Avbryt</button><button className="primary" disabled={busy||!title.trim()} onClick={()=>void save()}>{busy?'Sparar…':'Spara'}</button></div></div>}{!loading&&!editingId&&<div className="projectDocumentsList">{documents.map(item=><article className="projectDocumentRow" key={item.id}><div className="projectDocumentIdentity"><strong>{item.title}</strong>{item.description&&<small>{item.description}</small>}</div><div className="projectDocumentFiles">{item.attachments?.length?item.attachments.map(file=><button className="projectDocumentFileLink" key={file.id} disabled={openingId===file.id} onClick={()=>void openFile(file)}><span>{file.contentType.startsWith('image/')?'🖼':'📄'}</span><span><b>{file.originalName}</b><small>{openingId===file.id?'Öppnar…':formatBytes(file.sizeBytes)}</small></span></button>):<span className="projectDocumentNoFile">Ingen fil</span>}</div>{editMode&&<div className="projectDocumentEditActions"><button onClick={()=>edit(item)}>Byt namn</button><button className="danger" onClick={()=>void remove(item)}>Ta bort</button></div>}</article>)}{!documents.length&&<div className="projectSupportEmpty">Inga projektdokument har lagts in ännu.</div>}</div>}</section>
}
function filenameTitle(name:string){const trimmed=name.trim();const dot=trimmed.lastIndexOf('.');return dot>0?trimmed.slice(0,dot):trimmed}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${Math.round(value/1024)} kB`;return `${(value/(1024*1024)).toFixed(1)} MB`}
