const utilityItems=[
  {label:'Grafisk plan',icon:'🕸️'},
  {label:'Projektinformation',icon:'ℹ️'},
  {label:'Kontrollplan',icon:'📋'},
  {label:'Rapporter',icon:'📊'},
  {label:'Inställningar',icon:'⚙️'},
  {label:'Backup',icon:'💾'}
] as const;

type UtilityLabel=(typeof utilityItems)[number]['label'];
function projectRows(){return Array.from(document.querySelectorAll('.projectWorkspace .projectTreeRow')) as HTMLElement[]}
function rowLabel(row:HTMLElement){return row.querySelector('.projectTreeLabel')?.textContent?.trim()||''}
function findRow(label:UtilityLabel){return projectRows().find(row=>rowLabel(row)===label)||null}
function hideNativeUtilityRows(){for(const row of projectRows())if(utilityItems.some(item=>item.label===rowLabel(row)))row.style.display='none'}
function syncActive(){const activeLabel=projectRows().find(row=>row.classList.contains('selected'))?.querySelector('.projectTreeLabel')?.textContent?.trim()||'';const shell=document.querySelector<HTMLElement>('.studioShell');const projectPage=shell?.dataset.projectPage||'';const pageUtility=shell?.classList.contains('view-project-information')?'Projektinformation':shell?.classList.contains('view-project-reports')?'Rapporter':shell?.classList.contains('view-project-settings')?'Inställningar':projectPage==='information'?'Projektinformation':projectPage==='reports'?'Rapporter':projectPage==='settings'?'Inställningar':'';const nativeControlPlan=Boolean(document.querySelector('.studioShell.view-native-control-plan'));const graphicalPlan=Boolean(document.querySelector('.studioShell.view-graphical-plan'));const backup=Boolean(document.querySelector('.studioShell.view-backup'));const effectiveLabel=pageUtility||activeLabel;const utilityActive=utilityItems.some(item=>item.label===effectiveLabel);for(const button of Array.from(document.querySelectorAll<HTMLButtonElement>('.rail .projectUtilityRailButton')))button.classList.toggle('active',button.dataset.utilityLabel===effectiveLabel||(nativeControlPlan&&button.dataset.utilityLabel==='Kontrollplan')||(graphicalPlan&&button.dataset.utilityLabel==='Grafisk plan')||(backup&&button.dataset.utilityLabel==='Backup'));const workspace=document.querySelector<HTMLElement>('.projectWorkspace');workspace?.classList.toggle('projectUtilityView',utilityActive)}
function openUtility(label:UtilityLabel,attempt=0){if(label==='Grafisk plan'){window.dispatchEvent(new CustomEvent('byggplan:open-graphical-plan'));return}if(label==='Kontrollplan'){window.dispatchEvent(new CustomEvent('byggplan:open-control-plan'));return}if(label==='Backup'){window.dispatchEvent(new CustomEvent('byggplan:open-backup'));return}if(label==='Projektinformation'){window.dispatchEvent(new CustomEvent('byggplan:open-project-information'));return}if(label==='Rapporter'){window.dispatchEvent(new CustomEvent('byggplan:open-project-reports'));return}if(label==='Inställningar'){window.dispatchEvent(new CustomEvent('byggplan:open-project-settings'));return}hideNativeUtilityRows();const row=findRow(label);if(row){row.click();window.setTimeout(syncActive,30);return}const projectButton=document.querySelector<HTMLButtonElement>('.rail button[title="Projekt"]');if(projectButton&&!document.querySelector('.projectWorkspace'))projectButton.click();if(attempt<30)window.setTimeout(()=>openUtility(label,attempt+1),50)}
function wireUsers(rail:HTMLElement){const button=rail.querySelector<HTMLButtonElement>('button[title="Användare"]');if(!button)return;button.disabled=false;if(button.dataset.usersWired==='1')return;button.dataset.usersWired='1';button.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('byggplan:open-users')))}
function hasNativeButton(rail:HTMLElement,label:UtilityLabel){if(label==='Backup')return Boolean(rail.querySelector('button[title^="Backup"]:not(.projectUtilityRailButton)'));return false}
function ensureRailButtons(){const rails=Array.from(document.querySelectorAll<HTMLElement>('.rail'));for(const rail of rails){if(rail.classList.contains('kaRail'))continue;wireUsers(rail);const projectRail=Boolean(rail.closest('.projectWorkspace'));const systemAdmin=Boolean(document.querySelector('.studioShell.view-project[data-system-admin="true"]'));if(projectRail&&systemAdmin&&!rail.querySelector('.projectSystemRailButton')){const button=document.createElement('button');button.type='button';button.className='projectSystemRailButton';button.title='Systemadministration · Projektytor';button.innerHTML='<span class="projectUtilityRailIcon">🛡️</span><span>System</span>';button.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('byggplan:open-system')));rail.appendChild(button)}for(const item of utilityItems){if(rail.querySelector(`.projectUtilityRailButton[data-utility-label="${item.label}"]`)||hasNativeButton(rail,item.label))continue;const button=document.createElement('button');button.type='button';button.className='projectUtilityRailButton';button.title=item.label;button.dataset.utilityLabel=item.label;button.innerHTML=`<span class="projectUtilityRailIcon">${item.icon}</span><span>${item.label}</span>`;button.addEventListener('click',()=>openUtility(item.label));rail.appendChild(button)}}hideNativeUtilityRows();syncActive()}
export function installProjectUtilityRail(){ensureRailButtons();let scheduled=0;const observer=new MutationObserver(()=>{window.clearTimeout(scheduled);scheduled=window.setTimeout(ensureRailButtons,20)});observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})}
