import {useRef,useState} from 'react';
import JSZip from 'jszip';
import './project-backup.css';

type BackupFile={key:string;size:number;etag?:string;contentType?:string};
type PortableBackup={format:string;version:number;exportedAt:string;sourceProjectId:string;entities:Record<string,Record<string,unknown>[]>;files:BackupFile[]};
const API_BASE=(import.meta.env.VITE_API_BASE_URL||'https://api.byggplan.tunell.org').replace(/\/$/,'');
function slug(v:string){return v.toLocaleLowerCase('sv-SE').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'projekt'}
function clientState(projectId:string){const state:Record<string,string>={};try{for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.includes(projectId)){const value=localStorage.getItem(key);if(value!==null)state[key]=value;}}}catch{}return state}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function ProjectBackupView({projectId,projectName}:{projectId:string;projectName?:string}){
 const inputRef=useRef<HTMLInputElement|null>(null);const[busy,setBusy]=useState(false);const[progress,setProgress]=useState('');const[message,setMessage]=useState('');const[error,setError]=useState('');
 async function createBackup(){setBusy(true);setError('');setMessage('');try{setProgress('Samlar projektdata…');const r=await fetch(`${API_BASE}/api/studio/projects/${encodeURIComponent(projectId)}/backup-manifest`,{cache:'no-store'});const d=await r.json() as {ok?:boolean;backup?:PortableBackup;error?:string};if(!r.ok||!d.backup)throw new Error(d.error||'Kunde inte skapa backup.');const backup=d.backup;const zip=new JSZip();zip.file('backup.json',JSON.stringify(backup,null,2));zip.file('client-state.json',JSON.stringify({projectId,state:clientState(projectId)},null,2));zip.file('README.txt',`ByggPlan portable backup\nProjekt: ${projectName||projectId}\nSkapad: ${backup.exportedAt}\nFormat: ${backup.format} v${backup.version}\n\nbackup.json innehåller projektets data som JSON.\nfiles/ innehåller foton och dokument.\nclient-state.json innehåller lokal graf-layout och andra projektbundna klientinställningar.\n`);for(let i=0;i<backup.files.length;i++){const f=backup.files[i];setProgress(`Hämtar filer ${i+1}/${backup.files.length}…`);const fr=await fetch(`${API_BASE}/api/studio/projects/${encodeURIComponent(projectId)}/backup-file?key=${encodeURIComponent(f.key)}`,{cache:'no-store'});if(!fr.ok)throw new Error(`Kunde inte läsa fil ${f.key}`);zip.file(`files/${f.key}`,await fr.blob());}setProgress('Packar ZIP…');const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});const stamp=new Date().toISOString().slice(0,19).replace(/[:T]/g,'-');download(blob,`${slug(projectName||'byggplan')}-backup-${stamp}.zip`);setMessage(`Backup klar: ${backup.files.length} filer och ${Object.keys(backup.entities).length} datagrupper.`);setProgress('');}catch(e){setError(e instanceof Error?e.message:'Backupen misslyckades.');setProgress('')}finally{setBusy(false)}}
 async function restore(file:File){setBusy(true);setError('');setMessage('');try{setProgress('Läser backup…');const zip=await JSZip.loadAsync(file);const backupEntry=zip.file('backup.json');if(!backupEntry)throw new Error('backup.json saknas i ZIP-filen.');const backup=JSON.parse(await backupEntry.async('string')) as PortableBackup;if(backup.format!=='byggplan-portable-backup'||backup.version!==1)throw new Error('ZIP-filen är inte en giltig ByggPlan-backup.');const projectRows=backup.entities?.projects||[];const sourceName=String(projectRows[0]?.name||backup.sourceProjectId||'projektet');if(!window.confirm(`Återställa backupen för ”${sourceName}” till det valda projektet?\n\nNuvarande projektdata ersätts. Foton och dokument i backupen återställs också.`))return;for(let i=0;i<(backup.files||[]).length;i++){const f=backup.files[i];setProgress(`Återställer filer ${i+1}/${backup.files.length}…`);const entry=zip.file(`files/${f.key}`);if(!entry)throw new Error(`Filen saknas i backupen: ${f.key}`);const blob=await entry.async('blob');const form=new FormData();form.set('key',f.key.replace(`projects/${backup.sourceProjectId}/`,`projects/${projectId}/`));form.set('file',new File([blob],f.key.split('/').pop()||'backup-file',{type:f.contentType||blob.type||'application/octet-stream'}));const rr=await fetch(`${API_BASE}/api/studio/projects/${encodeURIComponent(projectId)}/restore-file`,{method:'POST',body:form});if(!rr.ok){const x=await rr.json().catch(()=>({})) as {error?:string};throw new Error(x.error||`Kunde inte återställa ${f.key}`);}}
 setProgress('Återställer projektdata…');const rr=await fetch(`${API_BASE}/api/studio/projects/${encodeURIComponent(projectId)}/restore-data`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup})});const rd=await rr.json().catch(()=>({})) as {ok?:boolean;error?:string};if(!rr.ok||!rd.ok)throw new Error(rd.error||'Kunde inte återställa projektdata.');const stateEntry=zip.file('client-state.json');if(stateEntry){const cs=JSON.parse(await stateEntry.async('string')) as {state?:Record<string,string>;projectId?:string};try{for(const[key,value]of Object.entries(cs.state||{})){const mapped=cs.projectId&&cs.projectId!==projectId?key.replaceAll(cs.projectId,projectId):key;localStorage.setItem(mapped,value);}}catch{}}
 setProgress('');setMessage('Återställningen är klar. Sidan laddas om för att läsa in den återställda projektinformationen.');setTimeout(()=>window.location.reload(),1400);}catch(e){setError(e instanceof Error?e.message:'Återställningen misslyckades.');setProgress('')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
 return <div className="projectBackupPage"><header><small>PROJEKTVERKTYG</small><h1>Backup och återställning</h1><p>Skapa en portabel ZIP-backup med projektdata i JSON-format samt alla foton och dokument. Backupen kan senare läsas tillbaka till ByggPlan.</p></header><div className="backupCards"><section><div className="backupIcon">↓</div><div><h2>Skapa backup</h2><p>Hämtar projektets struktur, aktiviteter, kontrollpunkter, dokumentation, inställningar och övrig projektdata. Alla filer i projektets fillagring läggs i samma ZIP.</p><button className="primary" disabled={busy} onClick={()=>void createBackup()}>{busy?'Arbetar…':'Ladda ner backup (.zip)'}</button></div></section><section className="restoreCard"><div className="backupIcon">↺</div><div><h2>Återställ backup</h2><p>Läser en tidigare ByggPlan-backup och ersätter informationen i det valda projektet. Detta påverkar inte andra projekt.</p><input ref={inputRef} type="file" accept=".zip,application/zip" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f)}}/><button disabled={busy} onClick={()=>inputRef.current?.click()}>Välj backupfil…</button><div className="restoreWarning"><b>Viktigt:</b> återställning ersätter nuvarande projektdata. Skapa gärna en ny backup först.</div></div></section></div>{progress&&<div className="backupProgress">{progress}</div>}{message&&<div className="backupMessage">✓ {message}</div>}{error&&<div className="backupError">⚠ {error}</div>}<section className="backupFormat"><h3>Backupformat</h3><code>backup.json</code><span>Projektdata i strukturerad JSON</span><code>files/</code><span>Alla foton, PDF:er, ritningar och övriga projektfiler</span><code>client-state.json</code><span>Grafens layout, beroenden och andra lokala projektinställningar</span></section></div>
}
