import { useEffect,useMemo,useState } from 'react';

type Condition={id:string;code:string;title?:string;description:string;section_code:string;section_title:string;item_type:string;governing_document_id:string;governing_document_title:string;document_type:string;issuer:string;reference:string;condition_kind?:string;source_type?:string};

export function ProjectConditionsView({projectId}:{projectId:string}){
 const[items,setItems]=useState<Condition[]>([]);const[message,setMessage]=useState('');const[loading,setLoading]=useState(true);const[adding,setAdding]=useState(false);const[title,setTitle]=useState('');const[description,setDescription]=useState('');
 async function load(){setLoading(true);setMessage('');try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/project-conditions`,{cache:'no-store'});const d=await r.json().catch(()=>({})) as {conditions?:Condition[];error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte läsa projektvillkor.');setItems(d.conditions||[])}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa projektvillkor.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[projectId]);
 const groups=useMemo(()=>{const m=new Map<string,{title:string;items:Condition[]}>();for(const item of items){const key=item.governing_document_id||item.governing_document_title||item.source_type||'project';const g=m.get(key)||{title:item.governing_document_title||'Projektspecifikt',items:[]};g.items.push(item);m.set(key,g)}return [...m.values()]},[items]);
 async function add(){if(!title.trim())return;setAdding(true);try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/project-conditions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.trim(),description:description.trim()})});const d=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(d.error||'Kunde inte skapa projektvillkoret.');setTitle('');setDescription('');await load()}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte skapa projektvillkoret.')}finally{setAdding(false)}}
 return <section className="projectConditions projectTabContent"><div className="projectTabHeader"><div><small>PROJEKTVILLKOR</small><h2>Stående instruktioner och villkor</h2><p>Krav som gäller fortlöpande under projektet och därför inte ska bockas av som vanliga aktiviteter. En befintlig aktivitet görs om till projektvillkor direkt i aktivitetens fält <b>Aktivitetstyp</b>.</p></div></div>
 {message&&<div className="projectSupportMessage">{message}</div>}
 <div className="projectConditionTools"><div className="projectConditionAdd"><h3>＋ Lägg till projektspecifikt villkor</h3><label><span>Rubrik</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Fuktskydda material och konstruktion under byggtid"/></label><label><span>Instruktion</span><textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Beskriv vad som ska gälla under projektet…"/></label><button className="primary" disabled={adding||!title.trim()} onClick={()=>void add()}>{adding?'Sparar…':'Lägg till villkor'}</button></div></div>
 {loading?<div className="projectSupportEmpty">Laddar projektvillkor…</div>:!items.length?<div className="projectSupportEmpty">Inga projektvillkor är registrerade ännu.</div>:<div className="projectConditionGroups">{groups.map(group=><section key={group.title} className="projectConditionGroup"><h3>{group.title}</h3>{group.items.map(item=><article key={`${item.condition_kind||''}:${item.id}`} className="projectConditionItem"><small>{[item.section_code,item.section_title,item.code].filter(Boolean).join(' · ')||'Projektspecifikt villkor'}</small>{item.title&&item.title!==item.description&&<strong>{item.title}</strong>}<p>{item.description||item.title}</p></article>)}</section>)}</div>}
 </section>;
}
