import { useEffect,useState } from 'react';

type Attachment={id:string;originalName:string;contentType:string;sizeBytes:number;url:string};
type ProjectDocument={id:string;title:string;description:string;attachments:Attachment[]};

export function ProjectDocumentsEditor({projectId}:{projectId:string}){
  const[documents,setDocuments]=useState<ProjectDocument[]>([]);const[loading,setLoading]=useState(true);const[editingId,setEditingId]=useState('');const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[uploadingId,setUploadingId]=useState('');const[pendingFile,setPendingFile]=useState<File|null>(null);
  useEffect(()=>{void load()},[projectId]);
  async function load(){setLoading(true);setMessage('');try{const r=await fetch(`/api/project-documents?projectId=${encodeURIComponent(projectId)}`,{cache:'no-store'});const raw=await r.text();let d:{documents?:ProjectDocument[];error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||'Kunde inte läsa projektdokument.');setDocuments(d.documents||[]);}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte läsa projektdokument.');}finally{setLoading(false)}}
  function newItem(){setEditingId('new');setTitle('');setDescription('');setPendingFile(null);setMessage('');}
  function edit(item:ProjectDocument){setEditingId(item.id);setTitle(item.title);setDescription(item.description||'');setPendingFile(null);setMessage('');}
  function cancel(){setEditingId('');setTitle('');setDescription('');setPendingFile(null);}
  async function uploadById(documentId:string,file:File){if(file.size>20*1024*1024)throw new Error('Filen får vara högst 20 MB.');const form=new FormData();form.append('file',file,file.name);const r=await fetch(`/api/studio/project-document-files/${encodeURIComponent(documentId)}`,{method:'POST',body:form});const raw=await r.text();if(raw.toLowerCase().includes('forsakringskassan.se/errorpage'))throw new Error('Nätverksfiltret blockerar filuppladdning till ByggPlan från detta nät.');let d:{error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||'Kunde inte ladda upp filen.');}
  async function save(){if(!title.trim())return;setBusy(true);setMessage('Sparar…');try{const isNew=editingId==='new';const r=await fetch(isNew?'/api/studio/project-documents':`/api/studio/project-documents/${editingId}`,{method:isNew?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(isNew?{projectId,title:title.trim(),description}:{title:title.trim(),description})});const raw=await r.text();let d:{id?:string;error?:string}={};try{d=raw?JSON.parse(raw):{}}catch{}if(!r.ok)throw new Error(d.error||raw||`Kunde inte spara projektdokumentet (HTTP ${r.status}).`);const documentId=isNew?d.id:editingId;if(isNew&&pendingFile&&documentId){setMessage('Dokumentet sparat. Laddar upp fil…');await uploadById(documentId,pendingFile);}cancel();await load();setMessage('Projektdokumentet är sparat.');window.setTimeout(()=>setMessage(''),1800);}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte spara projektdokumentet.');}finally{setBusy(false)}}
  async function upload(item:ProjectDocument,file:File){setUploadingId(item.id);setMessage('Laddar upp fil…');try{await uploadById(item.id,file);await load();setMessage('Filen är uppladdad.');window.setTimeout(()=>setMessage(''),1800);}catch(e){setMessage(e instanceof Error?e.message:'Kunde inte ladda upp filen.');}finally{setUploadingId('')}}
  async function removeFile(file:Attachment){if(!confirm(`Ta bort ”${file.originalName}”?`))return;const r=await fetch(`/api/studio/project-document-files/${encodeURIComponent(file.id)}`,{method:'DELETE'});if(r.ok)await load();}
  async function remove(item:ProjectDocument){if(!confirm(`Ta bort projektdokumentet ”${item.title}”?`))return;const r=await fetch(`/api/studio/project-documents/${encodeURIComponent(item.id)}`,{method:'DELETE'});if(r.ok)await load();}
  return <section className="projectDocumentsEditor"><div className="projectDocumentsHeader"><div><small>PROJEKTDOKUMENT</small><h2>Dokument för hela projektet</h2><p>Bygglov, kontrollplan, myndighetsbeslut, ritningspaket och andra dokument som gäller hela huset.</p></div><button className="primary" onClick={newItem}>＋ Nytt projektdokument</button></div>{message&&<div className="projectSupportMessage">{message}</div>}{loading&&<div className="projectSupportEmpty">Laddar projektdokument…</div>}{!loading&&editingId&&<div className="projectSupportForm"><label><span>Rubrik</span><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. Bygglov"/></label><label><span>Beskrivning</span><textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Valfri beskrivning…"/></label>{editingId==='new'&&<label className="projectSupportUpload"><input type="file" accept="image/*,application/pdf,.pdf" onChange={e=>{const file=e.target.files?.[0]||null;e.target.value='';setPendingFile(file)}}/><span>{pendingFile?`📎 ${pendingFile.name}`:'＋ Välj bild eller PDF'}</span></label>}<div><button onClick={cancel} disabled={busy}>Avbryt</button><button className="primary" disabled={busy||!title.trim()} onClick={()=>void save()}>{busy?'Sparar…':'Spara'}</button></div></div>}{!loading&&!editingId&&documents.map(item=><article className="projectSupportCard" key={item.id}><div className="projectSupportCardMain"><strong>{item.title}</strong>{item.description&&<p>{item.description}</p>}{item.attachments?.length>0&&<div className="projectSupportAttachments">{item.attachments.map(file=><div className="projectSupportAttachment" key={file.id}><a href={file.url} target="_blank" rel="noreferrer"><span>{file.contentType.startsWith('image/')?'🖼':'📄'}</span><span><b>{file.originalName}</b><small>{formatBytes(file.sizeBytes)}</small></span></a><button className="danger" onClick={()=>void removeFile(file)}>Ta bort</button></div>)}</div>}<label className={`projectSupportUpload ${uploadingId===item.id?'busy':''}`}><input type="file" accept="image/*,application/pdf,.pdf" disabled={Boolean(uploadingId)} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void upload(item,file)}}/><span>{uploadingId===item.id?'Laddar upp…':'＋ Lägg till bild eller PDF'}</span></label></div><div className="projectSupportCardActions"><button onClick={()=>edit(item)}>Redigera</button><button className="danger" onClick={()=>void remove(item)}>Ta bort</button></div></article>)}{!loading&&!editingId&&!documents.length&&<div className="projectSupportEmpty">Inga projektdokument har lagts in ännu.</div>}</section>
}
function formatBytes(value:number){if(value<1024)return `${value} B`;if(value<1024*1024)return `${Math.round(value/1024)} kB`;return `${(value/(1024*1024)).toFixed(1)} MB`}
