import {useEffect,useState,type FormEvent} from 'react';

type AvailableAttestation={roleCode:string;attestationType:'control'|'ka_review';label:string};
type Eligibility={canAttest?:boolean;performed?:boolean;fullyAttested?:boolean;controlComplete?:boolean;requiresKaReview?:boolean;kaReviewDone?:boolean;controllerRoles?:string[];controlAttestedRoles?:string[];missingControllerRoles?:string[];availableAttestations?:AvailableAttestation[];staleAttestationCount?:number};

export function ReportApprovalAction({projectId,itemId,onDone}:{projectId:string;itemId:string;responsibleRole?:string;onDone?:()=>void}){
 const[action,setAction]=useState<AvailableAttestation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[eligibility,setEligibility]=useState<Eligibility>({}),[loading,setLoading]=useState(true),[confirming,setConfirming]=useState(false),[password,setPassword]=useState('');
 async function refreshEligibility(){setLoading(true);try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/governing-attestations`,{cache:'no-store'});if(!r.ok)throw new Error('Kunde inte läsa kontrollstatus.');const x=await r.json() as {eligibility?:Record<string,Eligibility>};const next=x.eligibility?.[itemId];if(!next)throw new Error('Kontrollpunkten saknar aktuell atteststatus.');setEligibility(next);setAction((next.availableAttestations||[])[0]||null)}catch(e){setError(e instanceof Error?e.message:'Kunde inte läsa kontrollstatus.')}finally{setLoading(false)}}
 useEffect(()=>{setError('');void refreshEligibility();const changed=()=>void refreshEligibility();window.addEventListener('byggplan:activity-status-changed',changed);return()=>window.removeEventListener('byggplan:activity-status-changed',changed)},[projectId,itemId]);
 const canAttest=Boolean(!loading&&eligibility.canAttest&&action);
 function openConfirm(){if(!canAttest||!action)return;setPassword('');setError('');setConfirming(true)}
 async function approve(e:FormEvent){e.preventDefault();if(!canAttest||!action||!password)return;setBusy(true);setError('');try{const r=await fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/governing-items/${encodeURIComponent(itemId)}/attest`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({roleCode:action.roleCode,attestationType:action.attestationType,password})});const x=await r.json().catch(()=>({})) as {error?:string};if(!r.ok)throw new Error(x.error||'Kunde inte signera punkten.');setConfirming(false);setPassword('');await refreshEligibility();onDone?.()}catch(e){setError(e instanceof Error?e.message:'Kunde inte signera punkten.')}finally{setBusy(false)}}
 const missingControl=eligibility.missingControllerRoles||[];
 let waiting='Kontrollen är inte genomförd ännu.';
 if(eligibility.performed&&!eligibility.controlComplete)waiting=missingControl.length?`Väntar på kontrollintyg: ${missingControl.join(' + ')}`:'Väntar på kontrollintyg.';
 else if(eligibility.performed&&eligibility.controlComplete&&eligibility.requiresKaReview&&!eligibility.kaReviewDone)waiting='Kontrollintyget är klart · väntar på KA-signering.';
 else if(eligibility.fullyAttested)waiting='Kontrollpunktens signering är komplett.';
 const stale=Number(eligibility.staleAttestationCount||0)>0;
 return <div className={`reportApprovalAction ${canAttest?'ready':'locked'}`}>{stale&&!loading&&<small className="attestationStale">⚠ Tidigare signering är inaktuell – underlaget har ändrats.</small>}{loading?<small>Laddar kontrollstatus…</small>:canAttest&&action?<><span className="attestationRole">{action.label}</span><button disabled={busy} onClick={openConfirm}>{action.attestationType==='ka_review'?'✓ Signera som KA':'✓ Signera kontroll'}</button></>:<small className={eligibility.fullyAttested?'attestationComplete':''}>{waiting}</small>}{error&&!confirming&&<small>{error}</small>}{confirming&&action&&<div className="attestationDialogBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setConfirming(false)}}><form className="attestationDialog" onSubmit={approve}><header><div><small>ELEKTRONISK SIGNERING</small><h3>{action.attestationType==='ka_review'?'Signera som KA':'Signera kontrollintyg'}</h3></div><button type="button" aria-label="Stäng" disabled={busy} onClick={()=>setConfirming(false)}>×</button></header><p>Du signerar denna kontrollpunkt som <b>{action.roleCode}</b>. ByggPlan sparar din identitet, tidpunkt och ett kryptografiskt fingeravtryck av kontrollpunkten och dess aktuella underlag.</p><label>Bekräfta med ditt lösenord<input autoFocus type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="attestationDialogError">{error}</div>}<footer><button type="button" className="secondary" disabled={busy} onClick={()=>setConfirming(false)}>Avbryt</button><button disabled={busy||!password}>{busy?'Signerar…':'Signera'}</button></footer></form></div>}</div>
}
