import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';

type Approval={id:string;governing_item_id:string;signer_name:string;signer_email?:string;role_code:string;attestation_type?:string;signing_method?:string;content_hash?:string|null;signed_at:string};
function typeLabel(type:string|undefined,role:string){if(type==='ka_review')return'KA-signering';if(type==='control')return'Kontrollintyg';return role==='KA'?'Kontrollintyg':'Kontrollintyg'}
function methodLabel(a:Approval){if(a.signing_method==='password_reauth_sha256'&&a.content_hash)return'Lösenordsbekräftad · underlag låst med SHA-256';return'Äldre intern signering'}

type Props={items?:Approval[];loading?:boolean;projectId?:string;itemId?:string};
export function ReportApproval({items:providedItems,loading:providedLoading=false,projectId,itemId}:Props){
 const[fetchedItems,setFetchedItems]=useState<Approval[]>([]),[fetching,setFetching]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Approval|null>(null);
 const shouldFetch=providedItems===undefined&&Boolean(projectId&&itemId);
 useEffect(()=>{if(!shouldFetch||!projectId||!itemId)return;let active=true;setFetching(true);setError('');fetch(`/api/studio/projects/${encodeURIComponent(projectId)}/governing-attestations`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('Kunde inte läsa signeringarna.');return r.json() as Promise<{attestations?:Approval[]}>}).then(x=>{if(active)setFetchedItems((x.attestations||[]).filter(a=>a.governing_item_id===itemId))}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Kunde inte läsa signeringarna.')}).finally(()=>{if(active)setFetching(false)});return()=>{active=false}},[shouldFetch,projectId,itemId]);
 useEffect(()=>{if(!selected)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null)};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[selected]);
 const items=providedItems??fetchedItems,loading=providedItems!==undefined?providedLoading:fetching;
 const modal=selected?createPortal(<div className="attestationDialogBackdrop signatureModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="attestationDialog signatureDetails" role="dialog" aria-modal="true" aria-label="Signeringsdetaljer"><header><div><small>SIGNERINGSDETALJER</small><h3>{typeLabel(selected.attestation_type,selected.role_code)} · {selected.signer_name}</h3></div><button type="button" aria-label="Stäng" onClick={()=>setSelected(null)}>×</button></header><div className="signatureDetailRows"><div><small>Roll</small><b>{selected.role_code}</b></div><div><small>Tidpunkt</small><b>{selected.signed_at}</b></div><div><small>Signeringsmetod</small><b>{methodLabel(selected)}</b></div>{selected.signer_email&&<div><small>E-post</small><b>{selected.signer_email}</b></div>}{selected.content_hash&&<div><small>Fingeravtryck</small><code>{selected.content_hash}</code></div>}</div><footer><button type="button" onClick={()=>setSelected(null)}>Stäng</button></footer></div></div>,document.body):null;
 return <><div className="reportApproval"><small>SIGNERINGAR</small>{loading?<span>Laddar signeringar…</span>:error?<span>{error}</span>:items.length?<div className="signatureList">{items.map(a=><button type="button" key={a.id} className="signatureCompact" onClick={()=>setSelected(a)}><b>{typeLabel(a.attestation_type,a.role_code)} · {a.signer_name}</b><span>{a.role_code} · {a.signed_at}</span></button>)}</div>:<span>Ingen signering ännu</span>}</div>{modal}</>
}
