import {useRef,useState} from 'react';
import JSZip from 'jszip';
import './project-backup.css';

type SystemBackup={format:string;version:number;exportedAt:string;scope:string;entities:Record<string,Record<string,unknown>[]>};
const API_BASE=(import.meta.env.VITE_API_BASE_URL||'https://api.byggplan.tunell.org').replace(/\/$/,'');
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function SystemBackupView(){
 const inputRef=useRef<HTMLInputElement|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[error,setError]=useState('');
 async function createBackup(){setBusy(true);setMessage('');setError('');try{const r=await fetch(`${API_BASE}/api/studio/system/backup-manifest`,{cache:'no-store'});const d=await r.json() as {ok?:boolean;backup?:SystemBackup;error?:string};if(!r.ok||!d.backup)throw new Error(d.error||'Kunde inte skapa systembackup.');const zip=new JSZip();zip.file('system-backup.json',JSON.stringify(d.backup,null,2));zip.file('README.txt',`ByggPlan systembackup\nSkapad: ${d.backup.exportedAt}\nFormat: ${d.backup.format} v${d.backup.version}\n\nInnehåller generell masterdata som används för att skapa och underhålla projekt.\nInnehåller inte projektdata, projektfiler eller användarkonton.\n`);const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});const stamp=new Date().toISOString().slice(0,19).replace(/[:T]/g,'-');download(blob,`byggplan-systembackup-${stamp}.zip`);setMessage(`Systembackup klar: ${Object.keys(d.backup.entities).length} masterdatagrupper.`);}catch(e){setError(e instanceof Error?e.message:'Systembackupen misslyckades.')}finally{setBusy(false)}}
 async function restore(file:File){setBusy(true);setMessage('');setError('');try{const zip=await JSZip.loadAsync(file);const entry=zip.file('system-backup.json');if(!entry)throw new Error('system-backup.json saknas i ZIP-filen.');const backup=JSON.parse(await entry.async('string')) as SystemBackup;if(backup.format!=='byggplan-system-backup'||backup.version!==1||backup.scope!=='system-master-data')throw new Error('ZIP-filen är inte en giltig ByggPlan-systembackup.');if(!window.confirm('Återställa systemets masterdata från denna backup?\n\nNuvarande masterprojekt och tillhörande generell masterdata ersätts. Befintliga projekt påverkas inte.'))return;const r=await fetch(`${API_BASE}/api/studio/system/restore-data`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup})});const d=await r.json().catch(()=>({})) as {ok?:boolean;error?:string;tables?:string[]};if(!r.ok||!d.ok)throw new Error(d.error||'Kunde inte återställa systemdata.');setMessage(`Systemdata återställd: ${d.tables?.length||0} masterdatagrupper.`);}catch(e){setError(e instanceof Error?e.message:'Systemåterställningen misslyckades.')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}}
 return <div className="systemBackupSettings"><h3>Systembackup</h3><p>Backup av generell data som delas mellan projekt, framför allt masterprojekt, mastermoduler, mastermoment, masteraktiviteter och deras konfiguration. Projekt, projektfiler och användarkonton ingår inte.</p><div className="backupCards"><section><div className="backupIcon">↓</div><div><h2>Skapa systembackup</h2><p>Laddar ner masterdata som strukturerad JSON i en portabel ZIP-fil.</p><button className="primary" disabled={busy} onClick={()=>void createBackup()}>{busy?'Arbetar…':'Ladda ner systembackup'}</button></div></section><section className="restoreCard"><div className="backupIcon">↺</div><div><h2>Återställ systembackup</h2><p>Ersätter nuvarande masterdata. Befintliga projekt lämnas orörda.</p><input ref={inputRef} type="file" accept=".zip,application/zip" hidden disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void restore(f)}}/><button disabled={busy} onClick={()=>inputRef.current?.click()}>Välj systembackup…</button></div></section></div>{message&&<div className="backupMessage">✓ {message}</div>}{error&&<div className="backupError">⚠ {error}</div>}</div>;
}
