import {useEffect,useState,type FormEvent,type ReactNode} from 'react';
import './auth-gate.css';

type User={id:string;email:string;displayName:string;globalRoles:string[];projects:Array<{id:string;name:string;roles:string[]}>};
type Status={configured:boolean;bootstrapReady:boolean};

export function AuthGate({children}:{children:ReactNode}){
 const[status,setStatus]=useState<Status|null>(null),[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[changePassword,setChangePassword]=useState(false);
 async function load(){setLoading(true);setError('');try{const sr=await fetch('/api/auth/status',{cache:'no-store'});if(!sr.ok)throw new Error('Kunde inte läsa inloggningsstatus.');const s=await sr.json() as Status;setStatus(s);if(!s.configured){setUser(null);return}const mr=await fetch('/api/auth/me',{cache:'no-store'});if(mr.ok){const m=await mr.json() as {user:User};setUser(m.user)}else setUser(null)}catch(e){setError(e instanceof Error?e.message:'Kunde inte läsa inloggningen.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[]);
 if(loading)return <div className="authCenter"><div className="authCard"><b>ByggPlan Fält</b><p>Kontrollerar inloggning…</p></div></div>;
 if(error)return <div className="authCenter"><div className="authCard"><h1>ByggPlan Fält</h1><p className="authError">{error}</p><button onClick={()=>void load()}>Försök igen</button></div></div>;
 if(status&&!status.configured&&status.bootstrapReady)return <Bootstrap onDone={u=>{setUser(u);setStatus({...status,configured:true})}}/>;
 if(status&&!status.configured&&!status.bootstrapReady)return <>{children}<div className="authDevNotice">Inloggning ej aktiverad ännu</div></>;
 if(!user)return <Login onDone={setUser}/>;
 const isAdmin=user.globalRoles.includes('admin');const kaOnly=!isAdmin&&user.projects.length>0&&user.projects.every(p=>p.roles.includes('KA')&&!p.roles.some(r=>['BH','worker','supervisor'].includes(r)));
 if(kaOnly)return <div className="authCenter"><div className="authCard"><div className="authLogo">BP</div><small>KA-KONTO</small><h1>Kontrollplan i Studio</h1><p>Det här kontot har rollen Kontrollansvarig och arbetar i Kontrollplan-vyn i ByggPlan Studio.</p><a className="authPrimaryLink" href="https://studio.byggplan.tunell.org">Öppna ByggPlan Studio</a><button className="authSecondaryButton" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null)}}>Logga ut</button></div></div>;
 return <>{children}<div className="authUserBadge"><span><b>{user.displayName}</b><small>{user.email}</small></span><button onClick={()=>setChangePassword(true)}>Byt lösenord</button><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});setUser(null)}}>Logga ut</button></div>{changePassword&&<ChangePasswordModal onClose={()=>setChangePassword(false)}/>}</>;
}

function ChangePasswordModal({onClose}:{onClose:()=>void}){
 const[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(password!==confirm){setError('Lösenorden är inte lika.');return}setBusy(true);setError('');try{const r=await fetch('/api/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password,confirmPassword:confirm})});const x=await r.json().catch(()=>({})) as {ok?:boolean;error?:string};if(!r.ok||!x.ok)throw new Error(x.error||'Kunde inte byta lösenord.');setSaved(true);setPassword('');setConfirm('')}catch(e){setError(e instanceof Error?e.message:'Kunde inte byta lösenord.')}finally{setBusy(false)}}
 return <div className="authModalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><form className="authCard authPasswordCard" onSubmit={submit}><div className="authPasswordHead"><div><small>KONTO</small><h1>Byt lösenord</h1></div><button type="button" className="authCloseButton" onClick={onClose}>×</button></div>{saved?<><p>Lösenordet är ändrat. Du är fortfarande inloggad på den här enheten; andra gamla sessioner har loggats ut.</p><button type="button" onClick={onClose}>Klar</button></>:<><p>Du är redan inloggad, så du kan sätta ett nytt lösenord utan att ange det gamla.</p><label>Nytt lösenord<input type="password" autoComplete="new-password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Upprepa lösenord<input type="password" autoComplete="new-password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<p className="authError">{error}</p>}<div className="authPasswordActions"><button type="button" className="authSecondaryButton" onClick={onClose}>Avbryt</button><button disabled={busy}>{busy?'Sparar…':'Spara nytt lösenord'}</button></div></>}</form></div>
}

function Login({onDone}:{onDone:(user:User)=>void}){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const x=await r.json().catch(()=>({})) as {user?:User;error?:string};if(!r.ok||!x.user)throw new Error(x.error||'Inloggningen misslyckades.');onDone(x.user)}catch(e){setError(e instanceof Error?e.message:'Inloggningen misslyckades.')}finally{setBusy(false)}}return <div className="authCenter"><form className="authCard" onSubmit={submit}><div className="authLogo">BP</div><small>BYGGPLAN FÄLT</small><h1>Logga in</h1><label>E-post<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Lösenord<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="authError">{error}</p>}<button disabled={busy}>{busy?'Loggar in…':'Logga in'}</button></form></div>}

function Bootstrap({onDone}:{onDone:(user:User)=>void}){const[token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();if(password!==confirm){setError('Lösenorden är inte lika.');return}setBusy(true);setError('');try{const r=await fetch('/api/auth/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bootstrapToken:token,email,password})});const x=await r.json().catch(()=>({})) as {user?:User;error?:string};if(!r.ok||!x.user)throw new Error(x.error||'Kunde inte aktivera inloggningen.');onDone(x.user)}catch(e){setError(e instanceof Error?e.message:'Kunde inte aktivera inloggningen.')}finally{setBusy(false)}}return <div className="authCenter"><form className="authCard" onSubmit={submit}><div className="authLogo">BP</div><small>FÖRSTA INSTALLATION</small><h1>Aktivera inloggning</h1><p>Samma konto används i Studio och Fältappen.</p><label>Bootstrapnyckel<input type="password" value={token} onChange={e=>setToken(e.target.value)} required/></label><label>E-post<input type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Nytt lösenord<input type="password" autoComplete="new-password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/></label><label>Upprepa lösenord<input type="password" autoComplete="new-password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></label>{error&&<p className="authError">{error}</p>}<button disabled={busy}>{busy?'Aktiverar…':'Aktivera inloggning'}</button></form></div>}
